export type ThemeCategory = 
  | "all"
  | "dark" 
  | "light" 
  | "luxury" 
  | "cyber" 
  | "editorial" 
  | "creative"
  | "custom";

export interface ThemeTokens {
  id: string;
  name: string;
  description: string;
  isDark: boolean;
  category: "dark" | "light" | "luxury" | "cyber" | "editorial" | "creative" | "custom";
  bg: string;
  textMain: string;
  textSecondary: string;
  textMuted: string;
  cardBg: string;
  headerBg: string;
  pillBg: string;
  pillHover: string;
  pillBorder: string;
  border: string;
  accent: string;
  accentBg: string;
  accentHover: string;
  tabBg: string;
  tabActiveBg: string;
  tabActiveText: string;
  tabInactiveText: string;
  iconCircleBg: string;
  iconCircleColor: string;
  qrContainerBg: string;
  gradient: string;
  avatarBg: string;
  avatarBorder: string;
  divider: string;
  previewBg: string;
  previewAccent: string;
  previewSecondary?: string;
  hudGlow?: string;
  fontFamily?: string;
  cardRadius?: string;
  shadowStyle?: string;
  customCss?: string;
  isCustom?: boolean;
  isPublished?: boolean;
  featured?: boolean;
}

export const themes: Record<string, ThemeTokens> = {
  // 1. Apple Light (Clean / Light)
  "apple-light": {
    id: "apple-light",
    name: "Apple Light",
    description: "Crisp executive frost with California Blue",
    isDark: false,
    category: "light",
    bg: "bg-[#F5F5F7]",
    textMain: "text-[#1D1D1F]",
    textSecondary: "text-[#515154]",
    textMuted: "text-[#7C7C82]",
    cardBg: "bg-white/95 backdrop-blur-2xl shadow-xl",
    headerBg: "bg-white/90 backdrop-blur-xl",
    pillBg: "bg-[#F2F2F7]",
    pillHover: "hover:bg-[#E5E5EA]",
    pillBorder: "border-black/[0.08]",
    border: "border-black/[0.12]",
    accent: "text-[#0071E3]",
    accentBg: "bg-[#0071E3]",
    accentHover: "hover:bg-[#0077ED]",
    tabBg: "bg-[#EFEFF4]",
    tabActiveBg: "bg-white shadow-xs",
    tabActiveText: "text-[#1D1D1F] font-bold",
    tabInactiveText: "text-[#515154] hover:text-[#1D1D1F]",
    iconCircleBg: "bg-white shadow-xs",
    iconCircleColor: "text-[#1D1D1F]",
    qrContainerBg: "bg-[#F5F5F7]",
    gradient: "from-blue-100/70 via-purple-50/40 to-transparent",
    avatarBg: "bg-gradient-to-b from-neutral-100 via-neutral-50 to-neutral-200",
    avatarBorder: "border-white",
    divider: "bg-black/[0.08]",
    previewBg: "#F5F5F7",
    previewAccent: "#0071E3",
    previewSecondary: "#E5E5EA",
  },

  // 2. Apple Dark (Dark OLED)
  "apple-dark": {
    id: "apple-dark",
    name: "Apple Dark",
    description: "Pure pitch black with titanium gray & Cupertino Blue",
    isDark: true,
    category: "dark",
    bg: "bg-[#000000]",
    textMain: "text-[#FFFFFF]",
    textSecondary: "text-[#B0B0B5]",
    textMuted: "text-[#86868B]",
    cardBg: "bg-[#1C1C1E]/95 backdrop-blur-2xl shadow-2xl",
    headerBg: "bg-[#1C1C1E]/85 backdrop-blur-xl",
    pillBg: "bg-[#2C2C2E]",
    pillHover: "hover:bg-[#3A3A3C]",
    pillBorder: "border-white/[0.12]",
    border: "border-white/[0.15]",
    accent: "text-[#0A84FF]",
    accentBg: "bg-[#0A84FF]",
    accentHover: "hover:bg-[#0071E3]",
    tabBg: "bg-[#121214]",
    tabActiveBg: "bg-[#2C2C2E] shadow-sm",
    tabActiveText: "text-white font-bold",
    tabInactiveText: "text-[#B0B0B5] hover:text-white",
    iconCircleBg: "bg-[#2C2C2E]",
    iconCircleColor: "text-white",
    qrContainerBg: "bg-[#121214]",
    gradient: "from-blue-900/30 via-indigo-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-neutral-800 to-neutral-900",
    avatarBorder: "border-neutral-700",
    divider: "bg-white/[0.1]",
    previewBg: "#000000",
    previewAccent: "#0A84FF",
    previewSecondary: "#2C2C2E",
  },

  // 3. Neo-Brutalism Pop (New UI Skill)
  "neobrutalism-pop": {
    id: "neobrutalism-pop",
    name: "Neo-Brutalist Pop",
    description: "High-voltage canary yellow, 3px solid borders & 6px offset drop shadow",
    isDark: false,
    category: "creative",
    bg: "bg-[#FEF08A]",
    textMain: "text-[#0F172A] font-black",
    textSecondary: "text-[#334155] font-bold",
    textMuted: "text-[#64748B]",
    cardBg: "bg-white border-[3px] border-black shadow-[6px_6px_0px_#000000]",
    headerBg: "bg-[#FDE047] border-b-[3px] border-black",
    pillBg: "bg-[#F8FAFC] border-[2px] border-black shadow-[3px_3px_0px_#000000]",
    pillHover: "hover:bg-[#FDE047] hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[4px_4px_0px_#000000]",
    pillBorder: "border-black",
    border: "border-black",
    accent: "text-[#432DD7]",
    accentBg: "bg-[#432DD7] text-white border-[2px] border-black shadow-[3px_3px_0px_#000000]",
    accentHover: "hover:bg-[#321EB8] hover:shadow-[4px_4px_0px_#000000]",
    tabBg: "bg-[#F1F5F9] border-[2px] border-black",
    tabActiveBg: "bg-[#FDE047] text-black font-black border-[2px] border-black shadow-[2px_2px_0px_#000000]",
    tabActiveText: "text-black font-black",
    tabInactiveText: "text-[#475569] font-bold hover:text-black",
    iconCircleBg: "bg-white border-[2px] border-black shadow-[2px_2px_0px_#000000]",
    iconCircleColor: "text-black",
    qrContainerBg: "bg-[#FEF08A] border-[3px] border-black p-4 shadow-[4px_4px_0px_#000000]",
    gradient: "from-amber-200 via-yellow-100 to-transparent",
    avatarBg: "bg-[#FDE047]",
    avatarBorder: "border-[3px] border-black shadow-[4px_4px_0px_#000000]",
    divider: "bg-black h-[2px]",
    previewBg: "#FEF08A",
    previewAccent: "#432DD7",
    previewSecondary: "#FDE047",
    fontFamily: "font-sans font-black",
    cardRadius: "rounded-2xl",
    shadowStyle: "shadow-[6px_6px_0px_#000000]",
  },

  // 4. Claude Parchment (New UI Skill)
  "claude-parchment": {
    id: "claude-parchment",
    name: "Claude Parchment",
    description: "Warm ivory stone, authoritative slate ink & subtle terracotta clay accent",
    isDark: false,
    category: "editorial",
    bg: "bg-[#FAF9F5]",
    textMain: "text-[#141413]",
    textSecondary: "text-[#4D4C47]",
    textMuted: "text-[#7B7A74]",
    cardBg: "bg-[#FFFFFF] border border-[#E5E3DB] shadow-sm",
    headerBg: "bg-[#FAF9F5]/90 border-b border-[#E5E3DB]",
    pillBg: "bg-[#F3F1EB]",
    pillHover: "hover:bg-[#EBE8E0] hover:text-[#141413]",
    pillBorder: "border-[#E5E3DB]",
    border: "border-[#E5E3DB]",
    accent: "text-[#CC5A36]",
    accentBg: "bg-[#CC5A36]",
    accentHover: "hover:bg-[#B84E2E]",
    tabBg: "bg-[#F0EEE6]",
    tabActiveBg: "bg-white shadow-xs border border-[#E5E3DB]",
    tabActiveText: "text-[#141413] font-bold",
    tabInactiveText: "text-[#7B7A74] hover:text-[#141413]",
    iconCircleBg: "bg-[#F3F1EB]",
    iconCircleColor: "text-[#141413]",
    qrContainerBg: "bg-[#FAF9F5]",
    gradient: "from-orange-100/30 via-stone-100/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#F3F1EB] to-[#E5E3DB]",
    avatarBorder: "border-[#CC5A36]/40",
    divider: "bg-[#E5E3DB]",
    previewBg: "#FAF9F5",
    previewAccent: "#CC5A36",
    previewSecondary: "#141413",
    fontFamily: "font-sans",
    cardRadius: "rounded-xl",
  },

  // 5. Matrix Terminal (New UI Skill)
  "matrix-terminal": {
    id: "matrix-terminal",
    name: "Matrix Terminal",
    description: "Deep monochromatic cyber terminal with phosphor neon green telemetry",
    isDark: true,
    category: "cyber",
    bg: "bg-[#060A08]",
    textMain: "text-[#E6F4EA] font-mono",
    textSecondary: "text-[#2DB58A] font-mono",
    textMuted: "text-[#1A5C43] font-mono",
    cardBg: "bg-[#0A0F0D]/95 border border-[#14532D]/50 shadow-[0_0_30px_rgba(45,181,138,0.15)]",
    headerBg: "bg-[#0A0F0D] border-b border-[#14532D]/40",
    pillBg: "bg-[#0E1713]",
    pillHover: "hover:bg-[#15231D] hover:border-[#2DB58A]/60",
    pillBorder: "border-[#14532D]/60",
    border: "border-[#14532D]/50",
    accent: "text-[#00FF66]",
    accentBg: "bg-[#2DB58A]",
    accentHover: "hover:bg-[#00FF66] hover:text-black",
    tabBg: "bg-[#080D0B]",
    tabActiveBg: "bg-[#15231D] border border-[#2DB58A]/50",
    tabActiveText: "text-[#00FF66] font-mono font-bold",
    tabInactiveText: "text-[#2DB58A]/60 font-mono hover:text-[#00FF66]",
    iconCircleBg: "bg-[#0E1713] border border-[#2DB58A]/40",
    iconCircleColor: "text-[#00FF66]",
    qrContainerBg: "bg-[#080D0B] border border-[#2DB58A]/40",
    gradient: "from-emerald-950/60 via-green-950/30 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#0E1713] to-[#060A08]",
    avatarBorder: "border-[#00FF66]/60 shadow-[0_0_15px_rgba(0,255,102,0.3)]",
    divider: "bg-[#14532D]/50",
    previewBg: "#060A08",
    previewAccent: "#00FF66",
    previewSecondary: "#2DB58A",
    hudGlow: "rgba(45, 181, 138, 0.25)",
    fontFamily: "font-mono",
    cardRadius: "rounded-lg",
  },

  // 6. Claymorphism Pastel (New UI Skill)
  "clay-pastel": {
    id: "clay-pastel",
    name: "Claymorphism 3D",
    description: "Soft rounded marshmallow shapes with tactile puffy elevation & candy lavender",
    isDark: false,
    category: "creative",
    bg: "bg-[#EDE9FE]",
    textMain: "text-[#3B0764] font-bold",
    textSecondary: "text-[#6B21A8]",
    textMuted: "text-[#9333EA]/70",
    cardBg: "bg-white/90 backdrop-blur-xl border border-white/60 shadow-[0_20px_40px_rgba(139,92,246,0.18),inset_0_2px_4px_rgba(255,255,255,0.9)]",
    headerBg: "bg-white/80 backdrop-blur-md border-b border-purple-100",
    pillBg: "bg-[#FAF5FF] border border-purple-200/80 shadow-[0_4px_12px_rgba(147,51,234,0.08),inset_0_1px_2px_rgba(255,255,255,1)]",
    pillHover: "hover:bg-[#F3E8FF] hover:shadow-[0_8px_16px_rgba(147,51,234,0.15)]",
    pillBorder: "border-purple-200/80",
    border: "border-purple-200",
    accent: "text-[#8B5CF6]",
    accentBg: "bg-gradient-to-r from-[#8B5CF6] to-[#A855F7] shadow-[0_8px_20px_rgba(139,92,246,0.35)]",
    accentHover: "hover:brightness-110",
    tabBg: "bg-[#F3E8FF]/80 p-1.5",
    tabActiveBg: "bg-white shadow-[0_4px_10px_rgba(139,92,246,0.2)]",
    tabActiveText: "text-[#6B21A8] font-black",
    tabInactiveText: "text-[#A855F7] hover:text-[#6B21A8]",
    iconCircleBg: "bg-[#F5F3FF] shadow-[0_4px_10px_rgba(139,92,246,0.15)]",
    iconCircleColor: "text-[#7C3AED]",
    qrContainerBg: "bg-white p-4 shadow-[0_12px_24px_rgba(139,92,246,0.15)]",
    gradient: "from-purple-200 via-pink-100 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#FAF5FF] to-[#E9D5FF]",
    avatarBorder: "border-white shadow-[0_8px_24px_rgba(139,92,246,0.3)]",
    divider: "bg-purple-200/60",
    previewBg: "#EDE9FE",
    previewAccent: "#8B5CF6",
    previewSecondary: "#C084FC",
    cardRadius: "rounded-3xl",
  },

  // 7. Glassmorphic Aurora (New UI Skill)
  "glass-aurora": {
    id: "glass-aurora",
    name: "Glass Aurora",
    description: "Frosted glassmorphism with luminous emerald & cyan refraction glows",
    isDark: true,
    category: "creative",
    bg: "bg-[#03151A]",
    textMain: "text-white font-medium",
    textSecondary: "text-[#6EE7B7]",
    textMuted: "text-[#059669]",
    cardBg: "bg-[#042026]/75 backdrop-blur-3xl border border-emerald-500/30 shadow-[0_8px_32px_0_rgba(16,185,129,0.2)]",
    headerBg: "bg-[#042026]/60 backdrop-blur-2xl border-b border-emerald-500/20",
    pillBg: "bg-emerald-950/40 backdrop-blur-md",
    pillHover: "hover:bg-emerald-900/60 hover:border-emerald-400/50",
    pillBorder: "border-emerald-500/20",
    border: "border-emerald-500/30",
    accent: "text-[#34D399]",
    accentBg: "bg-gradient-to-r from-[#10B981] to-[#06B6D4] shadow-[0_0_20px_rgba(16,185,129,0.4)]",
    accentHover: "hover:shadow-[0_0_25px_rgba(6,182,212,0.6)]",
    tabBg: "bg-[#021014]/80",
    tabActiveBg: "bg-emerald-500/20 border border-emerald-400/40 text-white",
    tabActiveText: "text-[#34D399] font-bold",
    tabInactiveText: "text-emerald-300/60 hover:text-white",
    iconCircleBg: "bg-emerald-900/30 border border-emerald-500/30",
    iconCircleColor: "text-[#34D399]",
    qrContainerBg: "bg-[#021418]/90 border border-emerald-500/30",
    gradient: "from-emerald-600/20 via-cyan-600/10 to-transparent",
    avatarBg: "bg-gradient-to-b from-emerald-950 to-cyan-950",
    avatarBorder: "border-emerald-400/60 shadow-[0_0_25px_rgba(16,185,129,0.3)]",
    divider: "bg-emerald-500/20",
    previewBg: "#03151A",
    previewAccent: "#10B981",
    previewSecondary: "#06B6D4",
    hudGlow: "rgba(16, 185, 129, 0.3)",
    cardRadius: "rounded-3xl",
  },

  // 8. Terracotta Editorial (New UI Skill)
  "terracotta-editorial": {
    id: "terracotta-editorial",
    name: "Terracotta Warmth",
    description: "Sun-baked Tuscan clay, warm beige cream & deep ink serif typography",
    isDark: false,
    category: "editorial",
    bg: "bg-[#F5EDE4]",
    textMain: "text-[#3C2A21] font-serif",
    textSecondary: "text-[#634832]",
    textMuted: "text-[#8C6D58]",
    cardBg: "bg-[#FDFBF7] border border-[#E2D5C5] shadow-lg",
    headerBg: "bg-[#FDFBF7]/95 border-b border-[#E2D5C5]",
    pillBg: "bg-[#EFE6DC]",
    pillHover: "hover:bg-[#E5D7C9]",
    pillBorder: "border-[#DFD0BE]",
    border: "border-[#E2D5C5]",
    accent: "text-[#C85A32]",
    accentBg: "bg-[#C85A32]",
    accentHover: "hover:bg-[#B34D27]",
    tabBg: "bg-[#EFE6DC]",
    tabActiveBg: "bg-white shadow-xs border border-[#DFD0BE]",
    tabActiveText: "text-[#3C2A21] font-serif font-bold",
    tabInactiveText: "text-[#8C6D58] hover:text-[#3C2A21]",
    iconCircleBg: "bg-[#EFE6DC]",
    iconCircleColor: "text-[#C85A32]",
    qrContainerBg: "bg-[#F5EDE4]",
    gradient: "from-orange-200/40 via-amber-100/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#EFE6DC] to-[#DFD0BE]",
    avatarBorder: "border-[#C85A32]/40",
    divider: "bg-[#E2D5C5]",
    previewBg: "#F5EDE4",
    previewAccent: "#C85A32",
    previewSecondary: "#634832",
    fontFamily: "font-serif",
    cardRadius: "rounded-2xl",
  },

  // 9. Japanese Risograph Studio (New UI Skill)
  "riso-duotone": {
    id: "riso-duotone",
    name: "Riso Duotone Studio",
    description: "2-color risograph print aesthetic on off-white paper with scarlet & cyan spot inks",
    isDark: false,
    category: "creative",
    bg: "bg-[#F7F4EE]",
    textMain: "text-[#111625] font-black",
    textSecondary: "text-[#FF4A3D] font-bold",
    textMuted: "text-[#00A8B5]",
    cardBg: "bg-[#FFFFFF] border-2 border-[#111625] shadow-[4px_4px_0px_#FF4A3D]",
    headerBg: "bg-[#FFFFFF] border-b-2 border-[#111625]",
    pillBg: "bg-[#F7F4EE] border border-[#111625]",
    pillHover: "hover:bg-[#FF4A3D] hover:text-white hover:border-[#111625]",
    pillBorder: "border-[#111625]",
    border: "border-[#111625]",
    accent: "text-[#FF4A3D]",
    accentBg: "bg-[#FF4A3D] text-white border-2 border-[#111625]",
    accentHover: "hover:bg-[#00A8B5] hover:text-white",
    tabBg: "bg-[#EAE4D7] border border-[#111625]",
    tabActiveBg: "bg-[#FF4A3D] text-white font-black",
    tabActiveText: "text-white font-black",
    tabInactiveText: "text-[#111625] font-bold hover:text-[#FF4A3D]",
    iconCircleBg: "bg-[#F7F4EE] border border-[#111625]",
    iconCircleColor: "text-[#FF4A3D]",
    qrContainerBg: "bg-[#F7F4EE] border-2 border-[#111625] p-3 shadow-[3px_3px_0px_#00A8B5]",
    gradient: "from-red-100/50 via-teal-50/40 to-transparent",
    avatarBg: "bg-[#F7F4EE]",
    avatarBorder: "border-2 border-[#111625] shadow-[3px_3px_0px_#FF4A3D]",
    divider: "bg-[#111625]",
    previewBg: "#F7F4EE",
    previewAccent: "#FF4A3D",
    previewSecondary: "#00A8B5",
    cardRadius: "rounded-xl",
  },

  // 10. Sega 8-Bit Retro Arcade (New UI Skill)
  "sega-arcade": {
    id: "sega-arcade",
    name: "Sega Retro Arcade",
    description: "8-bit retro arcade cabinet with chunky tactile 3D buttons, EXP stats & cobalt blue",
    isDark: true,
    category: "creative",
    bg: "bg-[#0A0D2C]",
    textMain: "text-[#FFFFFF] font-mono",
    textSecondary: "text-[#38BDF8] font-mono",
    textMuted: "text-[#818CF8] font-mono",
    cardBg: "bg-[#101442] border-2 border-[#38BDF8] shadow-[0_0_20px_rgba(56,189,248,0.3)]",
    headerBg: "bg-[#171C5A] border-b-2 border-[#38BDF8]",
    pillBg: "bg-[#1C236B] border border-[#38BDF8]/60 shadow-[0_4px_0_#0D1138]",
    pillHover: "hover:bg-[#252E8C] hover:translate-y-[2px] hover:shadow-[0_2px_0_#0D1138]",
    pillBorder: "border-[#38BDF8]/60",
    border: "border-[#38BDF8]",
    accent: "text-[#F43F5E]",
    accentBg: "bg-[#F43F5E] shadow-[0_4px_0_#9F1239]",
    accentHover: "hover:bg-[#E11D48] hover:translate-y-[2px] hover:shadow-[0_2px_0_#9F1239]",
    tabBg: "bg-[#0A0E31] border border-[#38BDF8]/40",
    tabActiveBg: "bg-[#38BDF8] text-black font-black",
    tabActiveText: "text-black font-mono font-black",
    tabInactiveText: "text-[#38BDF8] font-mono hover:text-white",
    iconCircleBg: "bg-[#1C236B] border border-[#38BDF8]",
    iconCircleColor: "text-[#38BDF8]",
    qrContainerBg: "bg-[#0D1138] border-2 border-[#38BDF8]",
    gradient: "from-indigo-900/60 via-blue-900/30 to-transparent",
    avatarBg: "bg-[#1C236B]",
    avatarBorder: "border-2 border-[#F43F5E] shadow-[0_0_15px_rgba(244,63,94,0.5)]",
    divider: "bg-[#38BDF8]/40",
    previewBg: "#0A0D2C",
    previewAccent: "#38BDF8",
    previewSecondary: "#F43F5E",
    fontFamily: "font-mono",
    cardRadius: "rounded-none",
  },

  // 11. Bento Slate & Cobalt (New UI Skill)
  "bento-slate": {
    id: "bento-slate",
    name: "Bento Linear Grid",
    description: "Vercel & Linear inspired slate surface with glowing cobalt borders & high data density",
    isDark: true,
    category: "cyber",
    bg: "bg-[#0B0F17]",
    textMain: "text-[#F8FAFC] font-semibold",
    textSecondary: "text-[#94A3B8]",
    textMuted: "text-[#64748B]",
    cardBg: "bg-[#0F172A]/90 backdrop-blur-2xl border border-slate-800 shadow-2xl",
    headerBg: "bg-[#0F172A]/95 border-b border-slate-800",
    pillBg: "bg-[#1E293B]/80",
    pillHover: "hover:bg-[#334155] hover:border-sky-500/40",
    pillBorder: "border-slate-700/60",
    border: "border-slate-800",
    accent: "text-[#38BDF8]",
    accentBg: "bg-[#0284C7]",
    accentHover: "hover:bg-[#0369A1]",
    tabBg: "bg-[#0B0F17]",
    tabActiveBg: "bg-[#1E293B] border border-sky-500/30 text-white",
    tabActiveText: "text-[#38BDF8] font-bold",
    tabInactiveText: "text-[#94A3B8] hover:text-white",
    iconCircleBg: "bg-[#1E293B] border border-slate-700",
    iconCircleColor: "text-[#38BDF8]",
    qrContainerBg: "bg-[#0B0F17] border border-slate-800",
    gradient: "from-sky-900/30 via-slate-900/20 to-transparent",
    avatarBg: "bg-[#1E293B]",
    avatarBorder: "border-sky-500/40 shadow-[0_0_20px_rgba(56,189,248,0.2)]",
    divider: "bg-slate-800",
    previewBg: "#0B0F17",
    previewAccent: "#38BDF8",
    previewSecondary: "#1E293B",
    cardRadius: "rounded-2xl",
  },

  // 12. Dubai VIP Obsidian & 24K Gold (Luxury)
  "dubai-gold-vip": {
    id: "dubai-gold-vip",
    name: "Dubai 24K Gold VIP",
    description: "Ultra-luxury metallic brushed gold, deep obsidian carbon & VIP badge glow",
    isDark: true,
    category: "luxury",
    bg: "bg-[#050505]",
    textMain: "text-[#FAF5E6]",
    textSecondary: "text-[#D4AF37]",
    textMuted: "text-[#8A7840]",
    cardBg: "bg-[#0D0D0D]/95 border border-[#D4AF37]/40 shadow-[0_10px_40px_rgba(212,175,55,0.15)]",
    headerBg: "bg-[#121212]/95 border-b border-[#D4AF37]/30",
    pillBg: "bg-[#171717] border border-[#D4AF37]/30",
    pillHover: "hover:bg-[#221F14] hover:border-[#D4AF37]/70",
    pillBorder: "border-[#D4AF37]/30",
    border: "border-[#D4AF37]/40",
    accent: "text-[#D4AF37]",
    accentBg: "bg-gradient-to-r from-[#D4AF37] to-[#F3E5AB] text-black font-bold shadow-[0_0_20px_rgba(212,175,55,0.35)]",
    accentHover: "hover:brightness-110",
    tabBg: "bg-[#080808]",
    tabActiveBg: "bg-[#1C1A14] border border-[#D4AF37]/50 text-[#FAF5E6]",
    tabActiveText: "text-[#D4AF37] font-bold",
    tabInactiveText: "text-[#8A7840] hover:text-[#D4AF37]",
    iconCircleBg: "bg-[#171717] border border-[#D4AF37]/40",
    iconCircleColor: "text-[#D4AF37]",
    qrContainerBg: "bg-[#0A0A0A] border border-[#D4AF37]/40",
    gradient: "from-amber-950/40 via-yellow-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#221F14] to-[#0D0D0D]",
    avatarBorder: "border-[#D4AF37] shadow-[0_0_20px_rgba(212,175,55,0.4)]",
    divider: "bg-[#D4AF37]/20",
    previewBg: "#050505",
    previewAccent: "#D4AF37",
    previewSecondary: "#221F14",
    cardRadius: "rounded-2xl",
  },

  // 13. Fiction Storybook (New UI Skill)
  "fiction-storybook": {
    id: "fiction-storybook",
    name: "Storybook Fiction",
    description: "Warm cream, saturated brand color blocks & friendly rounded children's-book aesthetic",
    isDark: false,
    category: "creative",
    bg: "bg-[#FFFDF5]",
    textMain: "text-[#1E1B18] font-bold",
    textSecondary: "text-[#4A4036]",
    textMuted: "text-[#857463]",
    cardBg: "bg-white border-2 border-[#1E1B18] shadow-[4px_4px_0px_#F59E0B]",
    headerBg: "bg-[#FEF3C7] border-b-2 border-[#1E1B18]",
    pillBg: "bg-[#FFFBEB] border border-[#1E1B18]",
    pillHover: "hover:bg-[#FDE68A]",
    pillBorder: "border-[#1E1B18]",
    border: "border-[#1E1B18]",
    accent: "text-[#2563EB]",
    accentBg: "bg-[#2563EB] text-white border-2 border-[#1E1B18]",
    accentHover: "hover:bg-[#1D4ED8]",
    tabBg: "bg-[#F3EFE0] border border-[#1E1B18]",
    tabActiveBg: "bg-[#F59E0B] text-black font-black",
    tabActiveText: "text-black font-black",
    tabInactiveText: "text-[#4A4036] font-bold hover:text-black",
    iconCircleBg: "bg-[#FEF3C7] border border-[#1E1B18]",
    iconCircleColor: "text-[#1E1B18]",
    qrContainerBg: "bg-[#FFFBEB] border-2 border-[#1E1B18] p-3 shadow-[3px_3px_0px_#2563EB]",
    gradient: "from-amber-200/50 via-orange-100/30 to-transparent",
    avatarBg: "bg-[#FEF3C7]",
    avatarBorder: "border-2 border-[#1E1B18] shadow-[3px_3px_0px_#F59E0B]",
    divider: "bg-[#1E1B18]",
    previewBg: "#FFFDF5",
    previewAccent: "#2563EB",
    previewSecondary: "#F59E0B",
    cardRadius: "rounded-3xl",
  },

  // 14. Obsidian Gold (Luxury)
  "obsidian-gold": {
    id: "obsidian-gold",
    name: "Obsidian Gold",
    description: "Deep noir black with brilliant imperial 24K gold accents",
    isDark: true,
    category: "luxury",
    bg: "bg-[#0A0A0B]",
    textMain: "text-[#F5F5F7]",
    textSecondary: "text-[#D4AF37]",
    textMuted: "text-[#8A7A40]",
    cardBg: "bg-[#141416]/95 backdrop-blur-2xl border border-[#D4AF37]/30 shadow-2xl",
    headerBg: "bg-[#141416]/85 backdrop-blur-xl border-b border-[#D4AF37]/20",
    pillBg: "bg-[#1C1C20]",
    pillHover: "hover:bg-[#28282E]",
    pillBorder: "border-[#D4AF37]/30",
    border: "border-[#D4AF37]/30",
    accent: "text-[#D4AF37]",
    accentBg: "bg-gradient-to-r from-[#D4AF37] to-[#F3E5AB] text-black font-semibold",
    accentHover: "hover:brightness-110",
    tabBg: "bg-[#0E0E10]",
    tabActiveBg: "bg-[#222228] shadow-sm",
    tabActiveText: "text-[#D4AF37] font-bold",
    tabInactiveText: "text-[#B0B0B5] hover:text-[#D4AF37]",
    iconCircleBg: "bg-[#1C1C20] border border-[#D4AF37]/30",
    iconCircleColor: "text-[#D4AF37]",
    qrContainerBg: "bg-[#0E0E10]",
    gradient: "from-amber-900/30 via-yellow-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-neutral-800 to-neutral-900",
    avatarBorder: "border-[#D4AF37]/60",
    divider: "bg-[#D4AF37]/20",
    previewBg: "#0A0A0B",
    previewAccent: "#D4AF37",
    previewSecondary: "#28282E",
  },

  // 15. Emerald Forest (Luxury)
  "emerald-forest": {
    id: "emerald-forest",
    name: "Emerald Forest",
    description: "Deep pine green with lustrous mint and jade accents",
    isDark: true,
    category: "luxury",
    bg: "bg-[#061A14]",
    textMain: "text-[#F0FDF4]",
    textSecondary: "text-[#A7F3D0]",
    textMuted: "text-[#6EE7B7]",
    cardBg: "bg-[#0A261D]/95 backdrop-blur-2xl border border-emerald-500/20 shadow-2xl",
    headerBg: "bg-[#0A261D]/85 backdrop-blur-xl",
    pillBg: "bg-[#133E30]",
    pillHover: "hover:bg-[#1C5442]",
    pillBorder: "border-emerald-500/30",
    border: "border-emerald-500/30",
    accent: "text-[#10B981]",
    accentBg: "bg-[#10B981]",
    accentHover: "hover:bg-[#059669]",
    tabBg: "bg-[#061A14]",
    tabActiveBg: "bg-[#133E30] shadow-sm",
    tabActiveText: "text-white font-bold",
    tabInactiveText: "text-[#A7F3D0] hover:text-white",
    iconCircleBg: "bg-[#133E30]",
    iconCircleColor: "text-[#34D399]",
    qrContainerBg: "bg-[#061A14]",
    gradient: "from-emerald-900/30 via-teal-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-emerald-950 to-emerald-900",
    avatarBorder: "border-emerald-500/50",
    divider: "bg-emerald-500/20",
    previewBg: "#061A14",
    previewAccent: "#10B981",
    previewSecondary: "#133E30",
  },

  // 16. Royal Amethyst (Luxury)
  "royal-amethyst": {
    id: "royal-amethyst",
    name: "Royal Amethyst",
    description: "Velvety imperial purple with vibrant violet glow",
    isDark: true,
    category: "luxury",
    bg: "bg-[#0F081D]",
    textMain: "text-[#FAF5FF]",
    textSecondary: "text-[#E9D5FF]",
    textMuted: "text-[#C084FC]",
    cardBg: "bg-[#1A0E31]/95 backdrop-blur-2xl border border-purple-500/20 shadow-2xl",
    headerBg: "bg-[#1A0E31]/85 backdrop-blur-xl",
    pillBg: "bg-[#29174D]",
    pillHover: "hover:bg-[#3B226D]",
    pillBorder: "border-purple-500/30",
    border: "border-purple-500/30",
    accent: "text-[#A855F7]",
    accentBg: "bg-[#A855F7]",
    accentHover: "hover:bg-[#9333EA]",
    tabBg: "bg-[#0F081D]",
    tabActiveBg: "bg-[#29174D] shadow-sm",
    tabActiveText: "text-white font-bold",
    tabInactiveText: "text-[#E9D5FF] hover:text-white",
    iconCircleBg: "bg-[#29174D]",
    iconCircleColor: "text-[#C084FC]",
    qrContainerBg: "bg-[#0F081D]",
    gradient: "from-purple-900/30 via-fuchsia-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-purple-950 to-purple-900",
    avatarBorder: "border-purple-500/50",
    divider: "bg-purple-500/20",
    previewBg: "#0F081D",
    previewAccent: "#A855F7",
    previewSecondary: "#29174D",
  },

  // 17. Monaco Yacht (Luxury / Marine)
  "monaco-yacht": {
    id: "monaco-yacht",
    name: "Monaco Yacht",
    description: "Nautical deep midnight navy with platinum silver trim",
    isDark: true,
    category: "luxury",
    bg: "bg-[#0A1128]",
    textMain: "text-[#FFFFFF]",
    textSecondary: "text-[#93C5FD]",
    textMuted: "text-[#60A5FA]",
    cardBg: "bg-[#001F54]/95 backdrop-blur-2xl border border-blue-400/20 shadow-2xl",
    headerBg: "bg-[#001F54]/85 backdrop-blur-xl",
    pillBg: "bg-[#034078]",
    pillHover: "hover:bg-[#1282A2]",
    pillBorder: "border-blue-400/30",
    border: "border-blue-400/30",
    accent: "text-[#38BDF8]",
    accentBg: "bg-[#0284C7]",
    accentHover: "hover:bg-[#0369A1]",
    tabBg: "bg-[#0A1128]",
    tabActiveBg: "bg-[#034078] shadow-sm",
    tabActiveText: "text-white font-bold",
    tabInactiveText: "text-[#93C5FD] hover:text-white",
    iconCircleBg: "bg-[#034078]",
    iconCircleColor: "text-[#38BDF8]",
    qrContainerBg: "bg-[#0A1128]",
    gradient: "from-blue-900/30 via-sky-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-blue-950 to-blue-900",
    avatarBorder: "border-sky-400/50",
    divider: "bg-blue-400/20",
    previewBg: "#0A1128",
    previewAccent: "#38BDF8",
    previewSecondary: "#034078",
  },

  // 18. Rose Gold Luxury (Luxury)
  "rose-gold-luxury": {
    id: "rose-gold-luxury",
    name: "Rose Gold Luxury",
    description: "Refined blush noir with champagne rose gold accents",
    isDark: true,
    category: "luxury",
    bg: "bg-[#181114]",
    textMain: "text-[#FFF1F2]",
    textSecondary: "text-[#FECDD3]",
    textMuted: "text-[#FDA4AF]",
    cardBg: "bg-[#27171D]/95 backdrop-blur-2xl border border-rose-500/20 shadow-2xl",
    headerBg: "bg-[#27171D]/85 backdrop-blur-xl",
    pillBg: "bg-[#3D1E29]",
    pillHover: "hover:bg-[#542537]",
    pillBorder: "border-rose-500/30",
    border: "border-rose-500/30",
    accent: "text-[#FB7185]",
    accentBg: "bg-[#F43F5E]",
    accentHover: "hover:bg-[#E11D48]",
    tabBg: "bg-[#181114]",
    tabActiveBg: "bg-[#3D1E29] shadow-sm",
    tabActiveText: "text-white font-bold",
    tabInactiveText: "text-[#FECDD3] hover:text-white",
    iconCircleBg: "bg-[#3D1E29]",
    iconCircleColor: "text-[#FB7185]",
    qrContainerBg: "bg-[#181114]",
    gradient: "from-rose-900/30 via-pink-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-rose-950 to-rose-900",
    avatarBorder: "border-rose-400/50",
    divider: "bg-rose-500/20",
    previewBg: "#181114",
    previewAccent: "#FB7185",
    previewSecondary: "#3D1E29",
  },

  // 19. Cosmic Nebula (Cyber / Spatial)
  "cosmic-nebula": {
    id: "cosmic-nebula",
    name: "Cosmic Nebula",
    description: "Deep interstellar space with cyan and magenta photon trails",
    isDark: true,
    category: "cyber",
    bg: "bg-[#090514]",
    textMain: "text-[#F8FAFC]",
    textSecondary: "text-[#C084FC]",
    textMuted: "text-[#A855F7]",
    cardBg: "bg-[#120B24]/95 backdrop-blur-2xl border border-purple-500/30 shadow-2xl",
    headerBg: "bg-[#120B24]/85 backdrop-blur-xl",
    pillBg: "bg-[#21143D]",
    pillHover: "hover:bg-[#321F5A]",
    pillBorder: "border-cyan-400/30",
    border: "border-purple-500/30",
    accent: "text-[#22D3EE]",
    accentBg: "bg-gradient-to-r from-[#06B6D4] to-[#A855F7]",
    accentHover: "hover:brightness-110",
    tabBg: "bg-[#090514]",
    tabActiveBg: "bg-[#21143D] shadow-sm",
    tabActiveText: "text-[#22D3EE] font-bold",
    tabInactiveText: "text-[#C084FC] hover:text-[#22D3EE]",
    iconCircleBg: "bg-[#21143D]",
    iconCircleColor: "text-[#22D3EE]",
    qrContainerBg: "bg-[#090514]",
    gradient: "from-cyan-900/30 via-purple-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-purple-950 to-cyan-950",
    avatarBorder: "border-cyan-400/60",
    divider: "bg-purple-500/20",
    previewBg: "#090514",
    previewAccent: "#22D3EE",
    previewSecondary: "#21143D",
  },

  // 20. Titanium Slate (Dark Neutral)
  "titanium-slate": {
    id: "titanium-slate",
    name: "Titanium Slate",
    description: "Industrial dark carbon with precision chrome and neutral gray",
    isDark: true,
    category: "dark",
    bg: "bg-[#0F172A]",
    textMain: "text-[#F8FAFC]",
    textSecondary: "text-[#94A3B8]",
    textMuted: "text-[#64748B]",
    cardBg: "bg-[#1E293B]/95 backdrop-blur-2xl border border-slate-700/50 shadow-2xl",
    headerBg: "bg-[#1E293B]/85 backdrop-blur-xl",
    pillBg: "bg-[#334155]",
    pillHover: "hover:bg-[#475569]",
    pillBorder: "border-slate-600/50",
    border: "border-slate-700/50",
    accent: "text-[#38BDF8]",
    accentBg: "bg-[#0284C7]",
    accentHover: "hover:bg-[#0369A1]",
    tabBg: "bg-[#0F172A]",
    tabActiveBg: "bg-[#334155] shadow-sm",
    tabActiveText: "text-white font-bold",
    tabInactiveText: "text-[#94A3B8] hover:text-white",
    iconCircleBg: "bg-[#334155]",
    iconCircleColor: "text-white",
    qrContainerBg: "bg-[#0F172A]",
    gradient: "from-slate-800/40 via-slate-900/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-slate-800 to-slate-900",
    avatarBorder: "border-slate-600",
    divider: "bg-slate-700/50",
    previewBg: "#0F172A",
    previewAccent: "#38BDF8",
    previewSecondary: "#334155",
  },

  // 21. Neon Cyberpunk (Cyber)
  "neon-cyberpunk": {
    id: "neon-cyberpunk",
    name: "Neon Cyberpunk",
    description: "Electric lime & hyper-magenta under dark street neon lights",
    isDark: true,
    category: "cyber",
    bg: "bg-[#050505]",
    textMain: "text-[#FFFFFF]",
    textSecondary: "text-[#A3E635]",
    textMuted: "text-[#84CC16]",
    cardBg: "bg-[#111111]/95 backdrop-blur-2xl border border-lime-400/40 shadow-[0_0_30px_rgba(163,230,53,0.15)]",
    headerBg: "bg-[#111111]/85 backdrop-blur-xl",
    pillBg: "bg-[#1F1F1F]",
    pillHover: "hover:bg-[#2E2E2E]",
    pillBorder: "border-lime-400/40",
    border: "border-lime-400/40",
    accent: "text-[#A3E635]",
    accentBg: "bg-[#84CC16]",
    accentHover: "hover:bg-[#65A30D]",
    tabBg: "bg-[#050505]",
    tabActiveBg: "bg-[#1F1F1F] shadow-sm",
    tabActiveText: "text-[#A3E635] font-bold",
    tabInactiveText: "text-neutral-400 hover:text-[#A3E635]",
    iconCircleBg: "bg-[#1F1F1F]",
    iconCircleColor: "text-[#A3E635]",
    qrContainerBg: "bg-[#050505]",
    gradient: "from-lime-950/40 via-neutral-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-neutral-900 to-black",
    avatarBorder: "border-lime-400",
    divider: "bg-lime-400/20",
    previewBg: "#050505",
    previewAccent: "#A3E635",
    previewSecondary: "#1F1F1F",
  },

  // 22. Quantum Flux (Cyber)
  "quantum-flux": {
    id: "quantum-flux",
    name: "Quantum Flux",
    description: "Vibrant laser violet with blazing hyper-cyan grid",
    isDark: true,
    category: "cyber",
    bg: "bg-[#060412]",
    textMain: "text-[#F8FAFC]",
    textSecondary: "text-[#67E8F9]",
    textMuted: "text-[#22D3EE]",
    cardBg: "bg-[#0D0826]/95 backdrop-blur-2xl border border-cyan-500/30 shadow-2xl",
    headerBg: "bg-[#0D0826]/85 backdrop-blur-xl",
    pillBg: "bg-[#181045]",
    pillHover: "hover:bg-[#251966]",
    pillBorder: "border-cyan-400/30",
    border: "border-cyan-500/30",
    accent: "text-[#06B6D4]",
    accentBg: "bg-[#0891B2]",
    accentHover: "hover:bg-[#0E7490]",
    tabBg: "bg-[#060412]",
    tabActiveBg: "bg-[#181045] shadow-sm",
    tabActiveText: "text-[#67E8F9] font-bold",
    tabInactiveText: "text-[#A5B4FC] hover:text-[#67E8F9]",
    iconCircleBg: "bg-[#181045]",
    iconCircleColor: "text-[#06B6D4]",
    qrContainerBg: "bg-[#060412]",
    gradient: "from-cyan-900/30 via-indigo-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-indigo-950 to-cyan-950",
    avatarBorder: "border-cyan-400/60",
    divider: "bg-cyan-500/20",
    previewBg: "#060412",
    previewAccent: "#06B6D4",
    previewSecondary: "#181045",
  },

  // 23. Synthwave 80s (Creative)
  "synthwave-80s": {
    id: "synthwave-80s",
    name: "Synthwave 80s",
    description: "Miami sunset orange blending into deep retro neon purple",
    isDark: true,
    category: "creative",
    bg: "bg-[#130722]",
    textMain: "text-[#FFF1F2]",
    textSecondary: "text-[#FDE047]",
    textMuted: "text-[#F472B6]",
    cardBg: "bg-[#1F0E38]/95 backdrop-blur-2xl border border-pink-500/30 shadow-2xl",
    headerBg: "bg-[#1F0E38]/85 backdrop-blur-xl",
    pillBg: "bg-[#331859]",
    pillHover: "hover:bg-[#49227E]",
    pillBorder: "border-pink-500/30",
    border: "border-pink-500/30",
    accent: "text-[#F43F5E]",
    accentBg: "bg-gradient-to-r from-[#F43F5E] to-[#F59E0B]",
    accentHover: "hover:brightness-110",
    tabBg: "bg-[#130722]",
    tabActiveBg: "bg-[#331859] shadow-sm",
    tabActiveText: "text-[#FDE047] font-bold",
    tabInactiveText: "text-[#F472B6] hover:text-[#FDE047]",
    iconCircleBg: "bg-[#331859]",
    iconCircleColor: "text-[#F43F5E]",
    qrContainerBg: "bg-[#130722]",
    gradient: "from-pink-900/30 via-purple-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-pink-950 to-purple-950",
    avatarBorder: "border-pink-400/60",
    divider: "bg-pink-500/20",
    previewBg: "#130722",
    previewAccent: "#F43F5E",
    previewSecondary: "#331859",
  },

  // 24. Swiss Editorial (Editorial / Light)
  "swiss-editorial": {
    id: "swiss-editorial",
    name: "Swiss Editorial",
    description: "Bauhaus international typographic style with stark crimson red",
    isDark: false,
    category: "editorial",
    bg: "bg-[#EAE8E3]",
    textMain: "text-[#0A0A0A]",
    textSecondary: "text-[#3D3D3D]",
    textMuted: "text-[#666666]",
    cardBg: "bg-white border border-neutral-300 shadow-lg",
    headerBg: "bg-white border-b border-neutral-300",
    pillBg: "bg-[#F3F2EF]",
    pillHover: "hover:bg-[#E4E2DC]",
    pillBorder: "border-neutral-300",
    border: "border-neutral-300",
    accent: "text-[#E11D48]",
    accentBg: "bg-[#E11D48]",
    accentHover: "hover:bg-[#BE123C]",
    tabBg: "bg-[#EAE8E3]",
    tabActiveBg: "bg-white shadow-xs",
    tabActiveText: "text-[#0A0A0A] font-bold",
    tabInactiveText: "text-[#666666] hover:text-[#0A0A0A]",
    iconCircleBg: "bg-[#F3F2EF]",
    iconCircleColor: "text-[#0A0A0A]",
    qrContainerBg: "bg-[#EAE8E3]",
    gradient: "from-neutral-300/40 via-stone-200/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-neutral-200 to-neutral-300",
    avatarBorder: "border-neutral-400",
    divider: "bg-neutral-300",
    previewBg: "#EAE8E3",
    previewAccent: "#E11D48",
    previewSecondary: "#F3F2EF",
  },

  // 25. Tokyo Monochrome (Editorial / Dark)
  "tokyo-monochrome": {
    id: "tokyo-monochrome",
    name: "Tokyo Monochrome",
    description: "Pure Japanese minimalism with extreme ink contrast & vermilion touch",
    isDark: true,
    category: "editorial",
    bg: "bg-[#080808]",
    textMain: "text-[#FFFFFF]",
    textSecondary: "text-[#A3A3A3]",
    textMuted: "text-[#737373]",
    cardBg: "bg-[#121212] border border-neutral-800 shadow-2xl",
    headerBg: "bg-[#121212] border-b border-neutral-800",
    pillBg: "bg-[#1C1C1C]",
    pillHover: "hover:bg-[#282828]",
    pillBorder: "border-neutral-700",
    border: "border-neutral-800",
    accent: "text-[#EF4444]",
    accentBg: "bg-[#DC2626]",
    accentHover: "hover:bg-[#B91C1C]",
    tabBg: "bg-[#080808]",
    tabActiveBg: "bg-[#1C1C1C] shadow-sm",
    tabActiveText: "text-white font-bold",
    tabInactiveText: "text-[#A3A3A3] hover:text-white",
    iconCircleBg: "bg-[#1C1C1C]",
    iconCircleColor: "text-white",
    qrContainerBg: "bg-[#080808]",
    gradient: "from-neutral-900/40 via-stone-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-neutral-800 to-neutral-900",
    avatarBorder: "border-neutral-600",
    divider: "bg-neutral-800",
    previewBg: "#080808",
    previewAccent: "#EF4444",
    previewSecondary: "#1C1C1C",
  },

  // 26. Minimalist Glass (Editorial / Glass)
  "minimalist-glass": {
    id: "minimalist-glass",
    name: "Minimalist Glass",
    description: "Liquid crystal translucent slate with floating soft ambient glow",
    isDark: true,
    category: "editorial",
    bg: "bg-[#0A0D14]",
    textMain: "text-[#F1F5F9]",
    textSecondary: "text-[#94A3B8]",
    textMuted: "text-[#64748B]",
    cardBg: "bg-[#0F172A]/70 backdrop-blur-2xl border border-white/10 shadow-2xl",
    headerBg: "bg-[#0F172A]/60 backdrop-blur-xl",
    pillBg: "bg-white/5",
    pillHover: "hover:bg-white/10",
    pillBorder: "border-white/10",
    border: "border-white/10",
    accent: "text-[#60A5FA]",
    accentBg: "bg-[#3B82F6]",
    accentHover: "hover:bg-[#2563EB]",
    tabBg: "bg-[#0A0D14]/80",
    tabActiveBg: "bg-white/10 shadow-sm",
    tabActiveText: "text-white font-bold",
    tabInactiveText: "text-[#94A3B8] hover:text-white",
    iconCircleBg: "bg-white/5",
    iconCircleColor: "text-[#60A5FA]",
    qrContainerBg: "bg-[#0A0D14]/90",
    gradient: "from-blue-900/20 via-slate-900/10 to-transparent",
    avatarBg: "bg-gradient-to-b from-slate-800 to-slate-900",
    avatarBorder: "border-white/20",
    divider: "bg-white/10",
    previewBg: "#0A0D14",
    previewAccent: "#60A5FA",
    previewSecondary: "#1E293B",
  },

  // 27. Nordic Polar (Clean / Light)
  "nordic-polar": {
    id: "nordic-polar",
    name: "Nordic Polar",
    description: "Scandinavian ice white with ultra-deep arctic navy",
    isDark: false,
    category: "light",
    bg: "bg-[#F0F4F8]",
    textMain: "text-[#0F172A]",
    textSecondary: "text-[#334155]",
    textMuted: "text-[#64748B]",
    cardBg: "bg-white/95 backdrop-blur-2xl border border-slate-200 shadow-xl",
    headerBg: "bg-white/85 backdrop-blur-xl",
    pillBg: "bg-[#E2E8F0]",
    pillHover: "hover:bg-[#CBD5E1]",
    pillBorder: "border-slate-200",
    border: "border-slate-200",
    accent: "text-[#0284C7]",
    accentBg: "bg-[#0284C7]",
    accentHover: "hover:bg-[#0369A1]",
    tabBg: "bg-[#F0F4F8]",
    tabActiveBg: "bg-white shadow-xs",
    tabActiveText: "text-[#0F172A] font-bold",
    tabInactiveText: "text-[#64748B] hover:text-[#0F172A]",
    iconCircleBg: "bg-white shadow-xs",
    iconCircleColor: "text-[#0284C7]",
    qrContainerBg: "bg-[#F0F4F8]",
    gradient: "from-sky-100/60 via-slate-100/30 to-transparent",
    avatarBg: "bg-gradient-to-b from-slate-100 to-slate-200",
    avatarBorder: "border-slate-300",
    divider: "bg-slate-200",
    previewBg: "#F0F4F8",
    previewAccent: "#0284C7",
    previewSecondary: "#CBD5E1",
  },

  // 28. Matcha Latte (Creative / Light)
  "matcha-latte": {
    id: "matcha-latte",
    name: "Matcha Latte",
    description: "Calming Kyoto green tea foam over warm organic cream",
    isDark: false,
    category: "creative",
    bg: "bg-[#F3F6F1]",
    textMain: "text-[#1C2821]",
    textSecondary: "text-[#3E5244]",
    textMuted: "text-[#657F6D]",
    cardBg: "bg-[#FAFBF9]/95 backdrop-blur-2xl border border-[#D9E2D6] shadow-lg",
    headerBg: "bg-[#FAFBF9]/85 backdrop-blur-xl",
    pillBg: "bg-[#E5ECE2]",
    pillHover: "hover:bg-[#D5DFD1]",
    pillBorder: "border-[#D9E2D6]",
    border: "border-[#D9E2D6]",
    accent: "text-[#4A7C59]",
    accentBg: "bg-[#4A7C59]",
    accentHover: "hover:bg-[#3B6447]",
    tabBg: "bg-[#F3F6F1]",
    tabActiveBg: "bg-white shadow-xs",
    tabActiveText: "text-[#1C2821] font-bold",
    tabInactiveText: "text-[#657F6D] hover:text-[#1C2821]",
    iconCircleBg: "bg-[#E5ECE2]",
    iconCircleColor: "text-[#4A7C59]",
    qrContainerBg: "bg-[#F3F6F1]",
    gradient: "from-green-100/50 via-emerald-50/30 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#E5ECE2] to-[#D5DFD1]",
    avatarBorder: "border-[#AEC3A9]",
    divider: "bg-[#D9E2D6]",
    previewBg: "#F3F6F1",
    previewAccent: "#4A7C59",
    previewSecondary: "#D5DFD1",
  },

  // 29. Electric Coral (Creative / Dark)
  "electric-coral": {
    id: "electric-coral",
    name: "Electric Coral",
    description: "Hyper-vibrant hot coral orange with glowing obsidian depth",
    isDark: true,
    category: "creative",
    bg: "bg-[#0C0708]",
    textMain: "text-[#FFFFFF]",
    textSecondary: "text-[#FF8A65]",
    textMuted: "text-[#FF7043]",
    cardBg: "bg-[#170E10]/95 backdrop-blur-2xl border border-orange-500/20 shadow-2xl",
    headerBg: "bg-[#170E10]/85 backdrop-blur-xl",
    pillBg: "bg-[#29161B]",
    pillHover: "hover:bg-[#3D1E25]",
    pillBorder: "border-orange-500/30",
    border: "border-orange-500/30",
    accent: "text-[#FF5722]",
    accentBg: "bg-[#FF5722]",
    accentHover: "hover:bg-[#F4511E]",
    tabBg: "bg-[#0C0708]",
    tabActiveBg: "bg-[#29161B] shadow-sm",
    tabActiveText: "text-white font-bold",
    tabInactiveText: "text-[#FF8A65] hover:text-white",
    iconCircleBg: "bg-[#29161B]",
    iconCircleColor: "text-[#FF5722]",
    qrContainerBg: "bg-[#0C0708]",
    gradient: "from-orange-950/40 via-red-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-orange-950 to-neutral-950",
    avatarBorder: "border-orange-500/50",
    divider: "bg-orange-500/20",
    previewBg: "#0C0708",
    previewAccent: "#FF5722",
    previewSecondary: "#29161B",
  },

  // 30. IZN Minimalist
  "izn-minimalist": {
    id: "izn-minimalist",
    name: "IZN Minimalist",
    description: "Refined pure monochromatic aesthetic with clean structural whitespace",
    isDark: false,
    category: "light",
    bg: "bg-[#FAFAFA]",
    textMain: "text-[#171717]",
    textSecondary: "text-[#525252]",
    textMuted: "text-[#A3A3A3]",
    cardBg: "bg-white shadow-xl border border-neutral-200/80",
    headerBg: "bg-white/90 backdrop-blur-md",
    pillBg: "bg-[#F5F5F5]",
    pillHover: "hover:bg-[#E5E5E5]",
    pillBorder: "border-neutral-200",
    border: "border-neutral-200",
    accent: "text-[#171717]",
    accentBg: "bg-[#171717]",
    accentHover: "hover:bg-[#262626]",
    tabBg: "bg-[#F5F5F5]",
    tabActiveBg: "bg-white shadow-xs",
    tabActiveText: "text-[#171717] font-bold",
    tabInactiveText: "text-[#737373] hover:text-[#171717]",
    iconCircleBg: "bg-[#F5F5F5]",
    iconCircleColor: "text-[#171717]",
    qrContainerBg: "bg-[#FAFAFA]",
    gradient: "from-neutral-200/50 via-transparent to-transparent",
    avatarBg: "bg-neutral-100",
    avatarBorder: "border-white",
    divider: "bg-neutral-200",
    previewBg: "#FAFAFA",
    previewAccent: "#171717",
    previewSecondary: "#E5E5E5",
  },
  
  // 31. IZN Modern Bold
  "izn-modern-bold": {
    id: "izn-modern-bold",
    name: "Modern Bold",
    description: "High-contrast dark charcoal with electric gold neon highlights",
    isDark: true,
    category: "dark",
    bg: "bg-[#0A0A0A]",
    textMain: "text-white",
    textSecondary: "text-[#A3A3A3]",
    textMuted: "text-[#525252]",
    cardBg: "bg-[#141414] shadow-2xl border border-neutral-800",
    headerBg: "bg-[#141414]/90 backdrop-blur-md",
    pillBg: "bg-[#1F1F1F]",
    pillHover: "hover:bg-[#292929]",
    pillBorder: "border-neutral-700",
    border: "border-neutral-800",
    accent: "text-[#EAB308]",
    accentBg: "bg-[#EAB308] text-black font-bold",
    accentHover: "hover:bg-[#CA8A04]",
    tabBg: "bg-[#171717]",
    tabActiveBg: "bg-[#262626]",
    tabActiveText: "text-white font-bold",
    tabInactiveText: "text-[#A3A3A3] hover:text-white",
    iconCircleBg: "bg-[#262626]",
    iconCircleColor: "text-[#EAB308]",
    qrContainerBg: "bg-[#141414]",
    gradient: "from-yellow-500/10 via-transparent to-transparent",
    avatarBg: "bg-[#262626]",
    avatarBorder: "border-[#141414]",
    divider: "bg-white/10",
    previewBg: "#0A0A0A",
    previewAccent: "#EAB308",
    previewSecondary: "#262626",
  },
  
  // 32. IZN Corporate
  "izn-corporate": {
    id: "izn-corporate",
    name: "Corporate",
    description: "Professional enterprise navy blue with refined silver accents",
    isDark: true,
    category: "luxury",
    bg: "bg-[#091124]",
    textMain: "text-white",
    textSecondary: "text-[#94A3B8]",
    textMuted: "text-[#475569]",
    cardBg: "bg-[#0F172A] shadow-xl border border-blue-900/30",
    headerBg: "bg-[#0F172A]/95 backdrop-blur-sm",
    pillBg: "bg-[#1E293B]",
    pillHover: "hover:bg-[#334155]",
    pillBorder: "border-blue-800/20",
    border: "border-blue-900/40",
    accent: "text-[#38BDF8]",
    accentBg: "bg-[#0284C7]",
    accentHover: "hover:bg-[#0369A1]",
    tabBg: "bg-[#1E293B]/50",
    tabActiveBg: "bg-[#1E293B]",
    tabActiveText: "text-[#38BDF8] font-bold",
    tabInactiveText: "text-[#94A3B8] hover:text-[#E2E8F0]",
    iconCircleBg: "bg-[#1E293B]",
    iconCircleColor: "text-[#38BDF8]",
    qrContainerBg: "bg-[#0F172A]",
    gradient: "from-blue-900/30 via-slate-900/10 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#1E293B] to-[#0F172A]",
    avatarBorder: "border-[#0284C7]/50",
    divider: "bg-blue-900/30",
    previewBg: "#091124",
    previewAccent: "#0284C7",
    previewSecondary: "#1E293B",
  },
};

// Aliases for backwards-compatibility with previous cards
themes["midnight-glass"] = themes["titanium-slate"];
themes["sync-sphere"] = themes["cosmic-nebula"];

// In-memory dynamic custom themes registered at runtime
const dynamicCustomThemes: Record<string, ThemeTokens> = {};

export function registerCustomTheme(theme: ThemeTokens) {
  if (!theme || !theme.id) return;
  dynamicCustomThemes[theme.id] = { ...theme, isCustom: true };
}

export function getCustomThemes(): ThemeTokens[] {
  return Object.values(dynamicCustomThemes);
}

export function getAllThemes(customList?: ThemeTokens[]): ThemeTokens[] {
  const merged: Record<string, ThemeTokens> = { ...themes, ...dynamicCustomThemes };
  if (customList && Array.isArray(customList)) {
    customList.forEach(t => {
      if (t && t.id) {
        merged[t.id] = { ...t, isCustom: true };
      }
    });
  }
  return Object.values(merged).filter(
    (v, i, a) => a.findIndex(t => t.id === v.id) === i
  );
}

export function getThemeById(id: string, customList?: ThemeTokens[]): ThemeTokens {
  if (!id) return themes["apple-light"];
  if (customList && Array.isArray(customList)) {
    const found = customList.find(t => t.id === id);
    if (found) return found;
  }
  if (dynamicCustomThemes[id]) return dynamicCustomThemes[id];
  return themes[id] || themes["apple-light"];
}

export const themeList: ThemeTokens[] = Object.values(themes).filter(
  (v, i, a) => a.findIndex(t => t.id === v.id) === i
);

// Preset starter kits for the admin editor based on UI Skills
export const THEME_STARTER_PRESETS: { name: string; description: string; template: Partial<ThemeTokens> }[] = [
  {
    name: "Neo-Brutalist Electric",
    description: "3px black borders, vivid electric contrast, offset hard shadow",
    template: {
      category: "creative",
      isDark: false,
      bg: "bg-[#FEF08A]",
      textMain: "text-[#0F172A] font-black",
      textSecondary: "text-[#334155] font-bold",
      textMuted: "text-[#64748B]",
      cardBg: "bg-white border-[3px] border-black shadow-[6px_6px_0px_#000000]",
      headerBg: "bg-[#FDE047] border-b-[3px] border-black",
      pillBg: "bg-[#F8FAFC] border-[2px] border-black shadow-[3px_3px_0px_#000000]",
      pillHover: "hover:bg-[#FDE047]",
      pillBorder: "border-black",
      border: "border-black",
      accent: "text-[#432DD7]",
      accentBg: "bg-[#432DD7]",
      accentHover: "hover:bg-[#321EB8]",
      tabBg: "bg-[#F1F5F9] border-[2px] border-black",
      tabActiveBg: "bg-[#FDE047] text-black font-black",
      tabActiveText: "text-black font-black",
      tabInactiveText: "text-[#475569] font-bold",
      iconCircleBg: "bg-white border-[2px] border-black shadow-[2px_2px_0px_#000000]",
      iconCircleColor: "text-black",
      qrContainerBg: "bg-[#FEF08A] border-[3px] border-black",
      gradient: "from-amber-200 via-yellow-100 to-transparent",
      avatarBg: "bg-[#FDE047]",
      avatarBorder: "border-[3px] border-black shadow-[4px_4px_0px_#000000]",
      divider: "bg-black h-[2px]",
      previewBg: "#FEF08A",
      previewAccent: "#432DD7",
      previewSecondary: "#FDE047",
    }
  },
  {
    name: "Claude Warm Stone",
    description: "Ivory parchment aesthetic, Anthropic slate hierarchy, earthy clay accent",
    template: {
      category: "editorial",
      isDark: false,
      bg: "bg-[#FAF9F5]",
      textMain: "text-[#141413]",
      textSecondary: "text-[#4D4C47]",
      textMuted: "text-[#7B7A74]",
      cardBg: "bg-[#FFFFFF] border border-[#E5E3DB] shadow-sm",
      headerBg: "bg-[#FAF9F5]/90 border-b border-[#E5E3DB]",
      pillBg: "bg-[#F3F1EB]",
      pillHover: "hover:bg-[#EBE8E0]",
      pillBorder: "border-[#E5E3DB]",
      border: "border-[#E5E3DB]",
      accent: "text-[#CC5A36]",
      accentBg: "bg-[#CC5A36]",
      accentHover: "hover:bg-[#B84E2E]",
      tabBg: "bg-[#F0EEE6]",
      tabActiveBg: "bg-white shadow-xs border border-[#E5E3DB]",
      tabActiveText: "text-[#141413] font-bold",
      tabInactiveText: "text-[#7B7A74]",
      iconCircleBg: "bg-[#F3F1EB]",
      iconCircleColor: "text-[#141413]",
      qrContainerBg: "bg-[#FAF9F5]",
      gradient: "from-orange-100/30 via-stone-100/20 to-transparent",
      avatarBg: "bg-[#F3F1EB]",
      avatarBorder: "border-[#CC5A36]/40",
      divider: "bg-[#E5E3DB]",
      previewBg: "#FAF9F5",
      previewAccent: "#CC5A36",
      previewSecondary: "#141413",
    }
  },
  {
    name: "Cyber Terminal Phosphor",
    description: "Monospace telemetry, green HUD glow, hairline cyber borders",
    template: {
      category: "cyber",
      isDark: true,
      bg: "bg-[#060A08]",
      textMain: "text-[#E6F4EA] font-mono",
      textSecondary: "text-[#2DB58A] font-mono",
      textMuted: "text-[#1A5C43] font-mono",
      cardBg: "bg-[#0A0F0D]/95 border border-[#14532D]/50 shadow-[0_0_30px_rgba(45,181,138,0.15)]",
      headerBg: "bg-[#0A0F0D] border-b border-[#14532D]/40",
      pillBg: "bg-[#0E1713]",
      pillHover: "hover:bg-[#15231D]",
      pillBorder: "border-[#14532D]/60",
      border: "border-[#14532D]/50",
      accent: "text-[#00FF66]",
      accentBg: "bg-[#2DB58A]",
      accentHover: "hover:bg-[#00FF66]",
      tabBg: "bg-[#080D0B]",
      tabActiveBg: "bg-[#15231D] border border-[#2DB58A]/50",
      tabActiveText: "text-[#00FF66] font-mono font-bold",
      tabInactiveText: "text-[#2DB58A]/60 font-mono",
      iconCircleBg: "bg-[#0E1713] border border-[#2DB58A]/40",
      iconCircleColor: "text-[#00FF66]",
      qrContainerBg: "bg-[#080D0B] border border-[#2DB58A]/40",
      gradient: "from-emerald-950/60 via-green-950/30 to-transparent",
      avatarBg: "bg-[#0E1713]",
      avatarBorder: "border-[#00FF66]/60",
      divider: "bg-[#14532D]/50",
      previewBg: "#060A08",
      previewAccent: "#00FF66",
      previewSecondary: "#2DB58A",
    }
  },
  {
    name: "Claymorphism Lavender",
    description: "Marshmallow soft 3D elevation, pastel surfaces, puffy pill buttons",
    template: {
      category: "creative",
      isDark: false,
      bg: "bg-[#EDE9FE]",
      textMain: "text-[#3B0764] font-bold",
      textSecondary: "text-[#6B21A8]",
      textMuted: "text-[#9333EA]/70",
      cardBg: "bg-white/90 backdrop-blur-xl border border-white/60 shadow-[0_20px_40px_rgba(139,92,246,0.18)]",
      headerBg: "bg-white/80 border-b border-purple-100",
      pillBg: "bg-[#FAF5FF] border border-purple-200/80 shadow-[0_4px_12px_rgba(147,51,234,0.08)]",
      pillHover: "hover:bg-[#F3E8FF]",
      pillBorder: "border-purple-200/80",
      border: "border-purple-200",
      accent: "text-[#8B5CF6]",
      accentBg: "bg-[#8B5CF6]",
      accentHover: "hover:bg-[#7C3AED]",
      tabBg: "bg-[#F3E8FF]/80",
      tabActiveBg: "bg-white shadow-sm",
      tabActiveText: "text-[#6B21A8] font-black",
      tabInactiveText: "text-[#A855F7]",
      iconCircleBg: "bg-[#F5F3FF]",
      iconCircleColor: "text-[#7C3AED]",
      qrContainerBg: "bg-white shadow-sm",
      gradient: "from-purple-200 via-pink-100 to-transparent",
      avatarBg: "bg-[#FAF5FF]",
      avatarBorder: "border-white shadow-md",
      divider: "bg-purple-200/60",
      previewBg: "#EDE9FE",
      previewAccent: "#8B5CF6",
      previewSecondary: "#C084FC",
    }
  },
  {
    name: "Dubai Carbon & 24K Gold",
    description: "Ultra-luxury VIP obsidian, 24K metallic gold trim & high-end finish",
    template: {
      category: "luxury",
      isDark: true,
      bg: "bg-[#050505]",
      textMain: "text-[#FAF5E6]",
      textSecondary: "text-[#D4AF37]",
      textMuted: "text-[#8A7840]",
      cardBg: "bg-[#0D0D0D]/95 border border-[#D4AF37]/40 shadow-[0_10px_40px_rgba(212,175,55,0.15)]",
      headerBg: "bg-[#121212]/95 border-b border-[#D4AF37]/30",
      pillBg: "bg-[#171717] border border-[#D4AF37]/30",
      pillHover: "hover:bg-[#221F14]",
      pillBorder: "border-[#D4AF37]/30",
      border: "border-[#D4AF37]/40",
      accent: "text-[#D4AF37]",
      accentBg: "bg-[#D4AF37] text-black font-bold",
      accentHover: "hover:bg-[#C29D26]",
      tabBg: "bg-[#080808]",
      tabActiveBg: "bg-[#1C1A14] border border-[#D4AF37]/50",
      tabActiveText: "text-[#D4AF37] font-bold",
      tabInactiveText: "text-[#8A7840]",
      iconCircleBg: "bg-[#171717] border border-[#D4AF37]/40",
      iconCircleColor: "text-[#D4AF37]",
      qrContainerBg: "bg-[#0A0A0A] border border-[#D4AF37]/40",
      gradient: "from-amber-950/40 via-yellow-950/20 to-transparent",
      avatarBg: "bg-[#221F14]",
      avatarBorder: "border-[#D4AF37]",
      divider: "bg-[#D4AF37]/20",
      previewBg: "#050505",
      previewAccent: "#D4AF37",
      previewSecondary: "#221F14",
    }
  }
];
