export type ThemeCategory = 
  | "all"
  | "dark" 
  | "light" 
  | "luxury" 
  | "cyber" 
  | "editorial" 
  | "creative";

export interface ThemeTokens {
  id: string;
  name: string;
  description: string;
  isDark: boolean;
  category: "dark" | "light" | "luxury" | "cyber" | "editorial" | "creative";
  bg: string;
  textMain: string;
  textSecondary: string;
  textMuted: string;
  cardBg: string;
  headerBg: string;
  pillBg: string;
  pillHover: string;
  pillBorder: string;
  border: string;
  accent: string;
  accentBg: string;
  accentHover: string;
  tabBg: string;
  tabActiveBg: string;
  tabActiveText: string;
  tabInactiveText: string;
  iconCircleBg: string;
  iconCircleColor: string;
  qrContainerBg: string;
  gradient: string;
  avatarBg: string;
  avatarBorder: string;
  divider: string;
  previewBg: string;
  previewAccent: string;
  previewSecondary?: string;
  hudGlow?: string;
}

export const themes: Record<string, ThemeTokens> = {
  // 1. Apple Light
  "apple-light": {
    id: "apple-light",
    name: "Apple Light",
    description: "Crisp executive frost with California Blue",
    isDark: false,
    category: "light",
    bg: "bg-[#F5F5F7]",
    textMain: "text-[#1D1D1F]",
    textSecondary: "text-[#86868B]",
    textMuted: "text-[#A1A1A6]",
    cardBg: "bg-white/90 backdrop-blur-2xl",
    headerBg: "bg-white/80 backdrop-blur-xl",
    pillBg: "bg-[#F5F5F7]",
    pillHover: "hover:bg-[#E8E8ED]",
    pillBorder: "border-black/[0.06]",
    border: "border-black/[0.08]",
    accent: "text-[#0071E3]",
    accentBg: "bg-[#0071E3]",
    accentHover: "hover:bg-[#0077ED]",
    tabBg: "bg-[#EFEFF4]",
    tabActiveBg: "bg-white shadow-xs",
    tabActiveText: "text-[#1D1D1F] font-semibold",
    tabInactiveText: "text-[#86868B] hover:text-[#1D1D1F]",
    iconCircleBg: "bg-white shadow-xs",
    iconCircleColor: "text-[#1D1D1F]",
    qrContainerBg: "bg-[#F5F5F7]",
    gradient: "from-blue-100/60 via-purple-50/30 to-transparent",
    avatarBg: "bg-gradient-to-b from-neutral-100 via-neutral-50 to-neutral-200",
    avatarBorder: "border-white",
    divider: "bg-black/[0.06]",
    previewBg: "#F5F5F7",
    previewAccent: "#0071E3",
    previewSecondary: "#E5E5EA",
  },

  // 2. Apple Dark
  "apple-dark": {
    id: "apple-dark",
    name: "Apple Dark",
    description: "Pure pitch black with titanium gray & Cupertino Blue",
    isDark: true,
    category: "dark",
    bg: "bg-[#000000]",
    textMain: "text-white",
    textSecondary: "text-[#A1A1A6]",
    textMuted: "text-[#6E6E73]",
    cardBg: "bg-[#1C1C1E]/95 backdrop-blur-2xl",
    headerBg: "bg-[#1C1C1E]/80 backdrop-blur-xl",
    pillBg: "bg-[#2C2C2E]",
    pillHover: "hover:bg-[#3A3A3C]",
    pillBorder: "border-white/[0.08]",
    border: "border-white/[0.12]",
    accent: "text-[#0A84FF]",
    accentBg: "bg-[#0A84FF]",
    accentHover: "hover:bg-[#0071E3]",
    tabBg: "bg-[#121214]",
    tabActiveBg: "bg-[#2C2C2E] shadow-sm",
    tabActiveText: "text-white font-semibold",
    tabInactiveText: "text-[#8E8E93] hover:text-white",
    iconCircleBg: "bg-[#2C2C2E]",
    iconCircleColor: "text-white",
    qrContainerBg: "bg-[#121214]",
    gradient: "from-blue-900/30 via-indigo-950/20 to-transparent",
    avatarBg: "bg-gradient-to-b from-neutral-800 to-neutral-900",
    avatarBorder: "border-neutral-700",
    divider: "bg-white/[0.08]",
    previewBg: "#000000",
    previewAccent: "#0A84FF",
    previewSecondary: "#2C2C2E",
  },

  // 3. Obsidian Gold (Luxury)
  "obsidian-gold": {
    id: "obsidian-gold",
    name: "Obsidian Gold",
    description: "Luxury dark obsidian with champagne & metallic gold accents",
    isDark: true,
    category: "luxury",
    bg: "bg-[#0B0C10]",
    textMain: "text-[#F9F6EE]",
    textSecondary: "text-[#C5A880]",
    textMuted: "text-[#8E7E6B]",
    cardBg: "bg-[#14161D]/95 backdrop-blur-2xl",
    headerBg: "bg-[#14161D]/85 backdrop-blur-xl",
    pillBg: "bg-[#1E212B]",
    pillHover: "hover:bg-[#282C3A]",
    pillBorder: "border-[#D4AF37]/20",
    border: "border-[#D4AF37]/30",
    accent: "text-[#D4AF37]",
    accentBg: "bg-gradient-to-r from-[#D4AF37] to-[#AA7C11]",
    accentHover: "hover:brightness-110",
    tabBg: "bg-[#0F1117]",
    tabActiveBg: "bg-[#222634] shadow-sm border border-[#D4AF37]/25",
    tabActiveText: "text-[#F9F6EE] font-semibold",
    tabInactiveText: "text-[#A89A88] hover:text-[#F9F6EE]",
    iconCircleBg: "bg-[#1E212B] border border-[#D4AF37]/20",
    iconCircleColor: "text-[#D4AF37]",
    qrContainerBg: "bg-[#0F1117]",
    gradient: "from-[#D4AF37]/15 via-[#AA7C11]/5 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#1E212B] to-[#14161D]",
    avatarBorder: "border-[#D4AF37]/50",
    divider: "bg-[#D4AF37]/15",
    previewBg: "#0B0C10",
    previewAccent: "#D4AF37",
    previewSecondary: "#AA7C11",
  },

  // 4. Emerald Forest (Luxury)
  "emerald-forest": {
    id: "emerald-forest",
    name: "Emerald Forest",
    description: "Deep evergreen glass with vibrant mint accents",
    isDark: true,
    category: "luxury",
    bg: "bg-[#05130E]",
    textMain: "text-[#F0FDF4]",
    textSecondary: "text-[#86EFAC]",
    textMuted: "text-[#4ADE80]/60",
    cardBg: "bg-[#0A2219]/95 backdrop-blur-2xl",
    headerBg: "bg-[#0A2219]/85 backdrop-blur-xl",
    pillBg: "bg-[#103427]",
    pillHover: "hover:bg-[#164534]",
    pillBorder: "border-[#10B981]/20",
    border: "border-[#10B981]/25",
    accent: "text-[#34D399]",
    accentBg: "bg-[#10B981]",
    accentHover: "hover:bg-[#059669]",
    tabBg: "bg-[#061711]",
    tabActiveBg: "bg-[#144232] shadow-sm border border-[#10B981]/30",
    tabActiveText: "text-[#F0FDF4] font-semibold",
    tabInactiveText: "text-[#6EE7B7]/70 hover:text-white",
    iconCircleBg: "bg-[#103427] border border-[#10B981]/20",
    iconCircleColor: "text-[#34D399]",
    qrContainerBg: "bg-[#061711]",
    gradient: "from-[#10B981]/20 via-[#059669]/10 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#103427] to-[#0A2219]",
    avatarBorder: "border-[#10B981]/50",
    divider: "bg-[#10B981]/15",
    previewBg: "#05130E",
    previewAccent: "#10B981",
    previewSecondary: "#059669",
  },

  // 5. Royal Amethyst (Luxury)
  "royal-amethyst": {
    id: "royal-amethyst",
    name: "Royal Amethyst",
    description: "Imperial velvet purple, amethyst glow & 24K gold foil",
    isDark: true,
    category: "luxury",
    bg: "bg-[#0D0818]",
    textMain: "text-[#FBF8FF]",
    textSecondary: "text-[#D8B4FE]",
    textMuted: "text-[#A855F7]/60",
    cardBg: "bg-[#170E2B]/95 backdrop-blur-2xl",
    headerBg: "bg-[#170E2B]/85 backdrop-blur-xl",
    pillBg: "bg-[#251744]",
    pillHover: "hover:bg-[#311F5A]",
    pillBorder: "border-[#C084FC]/25",
    border: "border-[#EAB308]/30",
    accent: "text-[#FACC15]",
    accentBg: "bg-gradient-to-r from-[#9333EA] to-[#EAB308]",
    accentHover: "hover:brightness-115",
    tabBg: "bg-[#120B22]",
    tabActiveBg: "bg-[#2D1B52] shadow-sm border border-[#EAB308]/30",
    tabActiveText: "text-[#FACC15] font-semibold",
    tabInactiveText: "text-[#D8B4FE]/70 hover:text-white",
    iconCircleBg: "bg-[#251744] border border-[#EAB308]/20",
    iconCircleColor: "text-[#FACC15]",
    qrContainerBg: "bg-[#120B22]",
    gradient: "from-purple-900/30 via-amber-900/15 to-transparent",
    avatarBg: "bg-gradient-to-br from-[#2D1B52] to-[#120B22]",
    avatarBorder: "border-[#EAB308]/60",
    divider: "bg-[#EAB308]/15",
    previewBg: "#0D0818",
    previewAccent: "#9333EA",
    previewSecondary: "#EAB308",
  },

  // 6. Monaco Yacht (Luxury)
  "monaco-yacht": {
    id: "monaco-yacht",
    name: "Monaco Yacht",
    description: "Mediterranean azure blue, pure yacht white & warm bronze",
    isDark: false,
    category: "luxury",
    bg: "bg-[#F4F8FC]",
    textMain: "text-[#081F3E]",
    textSecondary: "text-[#3B628C]",
    textMuted: "text-[#7B9BBF]",
    cardBg: "bg-[#FFFFFF]/95 backdrop-blur-2xl",
    headerBg: "bg-[#FFFFFF]/85 backdrop-blur-xl",
    pillBg: "bg-[#E8F1FA]",
    pillHover: "hover:bg-[#D9E7F6]",
    pillBorder: "border-[#0052A3]/15",
    border: "border-[#C59B27]/30",
    accent: "text-[#0052A3]",
    accentBg: "bg-gradient-to-r from-[#0052A3] to-[#0077E6]",
    accentHover: "hover:brightness-110",
    tabBg: "bg-[#E5F0FA]",
    tabActiveBg: "bg-white shadow-xs border border-[#C59B27]/25",
    tabActiveText: "text-[#081F3E] font-semibold",
    tabInactiveText: "text-[#3B628C] hover:text-[#081F3E]",
    iconCircleBg: "bg-white shadow-xs border border-[#0052A3]/10",
    iconCircleColor: "text-[#0052A3]",
    qrContainerBg: "bg-[#E8F1FA]",
    gradient: "from-sky-100/60 via-amber-50/40 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#E8F1FA] to-[#D9E7F6]",
    avatarBorder: "border-[#C59B27]/50",
    divider: "bg-[#0052A3]/10",
    previewBg: "#F4F8FC",
    previewAccent: "#0052A3",
    previewSecondary: "#C59B27",
  },

  // 7. Rose Gold Luxury (Luxury)
  "rose-gold-luxury": {
    id: "rose-gold-luxury",
    name: "Rose Gold Quartz",
    description: "Silky blush cashmere, champagne quartz & rose gold",
    isDark: false,
    category: "luxury",
    bg: "bg-[#FDF8F7]",
    textMain: "text-[#3A1E24]",
    textSecondary: "text-[#8C5E68]",
    textMuted: "text-[#B88E97]",
    cardBg: "bg-[#FFFFFF]/95 backdrop-blur-2xl",
    headerBg: "bg-[#FFFFFF]/85 backdrop-blur-xl",
    pillBg: "bg-[#F8ECEB]",
    pillHover: "hover:bg-[#F2DCDC]",
    pillBorder: "border-[#E0A899]/30",
    border: "border-[#E0A899]/40",
    accent: "text-[#C86D7C]",
    accentBg: "bg-gradient-to-r from-[#C86D7C] to-[#E0A899]",
    accentHover: "hover:brightness-105",
    tabBg: "bg-[#F5E6E5]",
    tabActiveBg: "bg-white shadow-xs",
    tabActiveText: "text-[#3A1E24] font-semibold",
    tabInactiveText: "text-[#8C5E68] hover:text-[#3A1E24]",
    iconCircleBg: "bg-white shadow-xs",
    iconCircleColor: "text-[#C86D7C]",
    qrContainerBg: "bg-[#F8ECEB]",
    gradient: "from-rose-100/50 via-pink-50/40 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#F8ECEB] to-[#F2DCDC]",
    avatarBorder: "border-[#E0A899]/60",
    divider: "bg-[#E0A899]/20",
    previewBg: "#FDF8F7",
    previewAccent: "#C86D7C",
    previewSecondary: "#E0A899",
  },

  // 8. Cosmic Nebula (Cyber / High-Tech)
  "cosmic-nebula": {
    id: "cosmic-nebula",
    name: "Cosmic Nebula",
    description: "Midnight velvet violet with radiant purple & neon pink",
    isDark: true,
    category: "cyber",
    bg: "bg-[#0A0714]",
    textMain: "text-[#FAF5FF]",
    textSecondary: "text-[#C084FC]",
    textMuted: "text-[#9333EA]/70",
    cardBg: "bg-[#140E26]/95 backdrop-blur-2xl",
    headerBg: "bg-[#140E26]/85 backdrop-blur-xl",
    pillBg: "bg-[#1F153B]",
    pillHover: "hover:bg-[#2A1D4E]",
    pillBorder: "border-[#8B5CF6]/20",
    border: "border-[#8B5CF6]/30",
    accent: "text-[#A855F7]",
    accentBg: "bg-gradient-to-r from-[#8B5CF6] to-[#EC4899]",
    accentHover: "hover:brightness-110",
    tabBg: "bg-[#0E091D]",
    tabActiveBg: "bg-[#251A45] shadow-sm border border-[#8B5CF6]/30",
    tabActiveText: "text-white font-semibold",
    tabInactiveText: "text-[#C084FC]/70 hover:text-white",
    iconCircleBg: "bg-[#1F153B] border border-[#8B5CF6]/20",
    iconCircleColor: "text-[#C084FC]",
    qrContainerBg: "bg-[#0E091D]",
    gradient: "from-[#8B5CF6]/25 via-[#EC4899]/15 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#2A1D4E] to-[#140E26]",
    avatarBorder: "border-[#8B5CF6]/50",
    divider: "bg-[#8B5CF6]/15",
    previewBg: "#0A0714",
    previewAccent: "#8B5CF6",
    previewSecondary: "#EC4899",
  },

  // 9. Titanium Slate (Cyber / High-Tech)
  "titanium-slate": {
    id: "titanium-slate",
    name: "Titanium Slate",
    description: "Warm graphite and matte slate with cyan glow",
    isDark: true,
    category: "cyber",
    bg: "bg-[#121417]",
    textMain: "text-[#F1F5F9]",
    textSecondary: "text-[#94A3B8]",
    textMuted: "text-[#64748B]",
    cardBg: "bg-[#1A1D23]/95 backdrop-blur-2xl",
    headerBg: "bg-[#1A1D23]/85 backdrop-blur-xl",
    pillBg: "bg-[#242932]",
    pillHover: "hover:bg-[#2E3440]",
    pillBorder: "border-white/[0.08]",
    border: "border-cyan-500/25",
    accent: "text-[#06B6D4]",
    accentBg: "bg-[#06B6D4]",
    accentHover: "hover:bg-[#0891B2]",
    tabBg: "bg-[#14171D]",
    tabActiveBg: "bg-[#262C36] shadow-sm border border-cyan-500/30",
    tabActiveText: "text-white font-semibold",
    tabInactiveText: "text-[#94A3B8] hover:text-white",
    iconCircleBg: "bg-[#242932]",
    iconCircleColor: "text-[#06B6D4]",
    qrContainerBg: "bg-[#14171D]",
    gradient: "from-cyan-900/25 via-slate-900/30 to-transparent",
    avatarBg: "bg-gradient-to-b from-neutral-700 to-neutral-800",
    avatarBorder: "border-cyan-500/40",
    divider: "bg-white/[0.08]",
    previewBg: "#121417",
    previewAccent: "#06B6D4",
    previewSecondary: "#64748B",
  },

  // 10. Neon Cyberpunk (Cyber / High-Tech)
  "neon-cyberpunk": {
    id: "neon-cyberpunk",
    name: "Neon Cyberpunk",
    description: "High-contrast dark mode with glowing neon accents",
    isDark: true,
    category: "cyber",
    bg: "bg-[#09090b]",
    textMain: "text-[#f8fafc]",
    textSecondary: "text-[#22d3ee]",
    textMuted: "text-[#334155]",
    cardBg: "bg-[#0f172a]/85 backdrop-blur-3xl border-t border-[#22d3ee]/40",
    headerBg: "bg-[#0f172a]/70 backdrop-blur-xl",
    pillBg: "bg-[#1e293b]/60 backdrop-blur-md",
    pillHover: "hover:bg-[#1e293b] hover:shadow-[0_0_15px_rgba(34,211,238,0.3)]",
    pillBorder: "border-[#22d3ee]/30",
    border: "border-[#22d3ee]/40",
    accent: "text-[#0ea5e9]",
    accentBg: "bg-gradient-to-r from-[#0ea5e9] to-[#22d3ee] shadow-[0_0_20px_rgba(34,211,238,0.4)]",
    accentHover: "hover:brightness-125",
    tabBg: "bg-[#020617]/70",
    tabActiveBg: "bg-[#1e293b] shadow-[0_0_10px_rgba(34,211,238,0.2)] border border-[#22d3ee]/40",
    tabActiveText: "text-[#22d3ee] font-bold tracking-wide",
    tabInactiveText: "text-[#64748b] hover:text-[#f8fafc]",
    iconCircleBg: "bg-[#0f172a] border border-[#22d3ee]/40 shadow-[0_0_10px_rgba(34,211,238,0.2)]",
    iconCircleColor: "text-[#22d3ee]",
    qrContainerBg: "bg-[#0f172a]/70 backdrop-blur-md border border-[#22d3ee]/20",
    gradient: "from-[#0ea5e9]/25 via-[#22d3ee]/15 to-transparent",
    avatarBg: "bg-gradient-to-br from-[#0ea5e9] to-[#22d3ee]",
    avatarBorder: "border-[#020617]",
    divider: "bg-[#22d3ee]/25",
    previewBg: "#09090b",
    previewAccent: "#22d3ee",
    previewSecondary: "#0ea5e9",
    hudGlow: "shadow-[0_0_25px_rgba(34,211,238,0.25)]",
  },

  // 11. Quantum Flux (Cyber / High-Tech)
  "quantum-flux": {
    id: "quantum-flux",
    name: "Quantum Flux",
    description: "Void black, electric ultraviolet & solar amber flare",
    isDark: true,
    category: "cyber",
    bg: "bg-[#06070B]",
    textMain: "text-[#F8FAFC]",
    textSecondary: "text-[#A78BFA]",
    textMuted: "text-[#6366F1]/60",
    cardBg: "bg-[#0E111B]/95 backdrop-blur-2xl",
    headerBg: "bg-[#0E111B]/85 backdrop-blur-xl",
    pillBg: "bg-[#181D2E]",
    pillHover: "hover:bg-[#232B42]",
    pillBorder: "border-[#6366F1]/30",
    border: "border-[#F59E0B]/30",
    accent: "text-[#F59E0B]",
    accentBg: "bg-gradient-to-r from-[#6366F1] to-[#F59E0B]",
    accentHover: "hover:brightness-115",
    tabBg: "bg-[#0A0D16]",
    tabActiveBg: "bg-[#20273D] shadow-sm border border-[#F59E0B]/30",
    tabActiveText: "text-[#F59E0B] font-semibold",
    tabInactiveText: "text-[#A78BFA]/70 hover:text-white",
    iconCircleBg: "bg-[#181D2E] border border-[#6366F1]/30",
    iconCircleColor: "text-[#F59E0B]",
    qrContainerBg: "bg-[#0A0D16]",
    gradient: "from-indigo-900/30 via-amber-900/15 to-transparent",
    avatarBg: "bg-gradient-to-br from-[#6366F1] to-[#F59E0B]",
    avatarBorder: "border-[#F59E0B]/60",
    divider: "bg-[#6366F1]/20",
    previewBg: "#06070B",
    previewAccent: "#6366F1",
    previewSecondary: "#F59E0B",
  },

  // 12. Synthwave 80s (Cyber / Creative)
  "synthwave-80s": {
    id: "synthwave-80s",
    name: "Synthwave 80s",
    description: "Retro wireframe black, sunset fuchsia & vaporwave cyan",
    isDark: true,
    category: "cyber",
    bg: "bg-[#120826]",
    textMain: "text-[#FFFFFF]",
    textSecondary: "text-[#F472B6]",
    textMuted: "text-[#38BDF8]/70",
    cardBg: "bg-[#1C0E38]/90 backdrop-blur-2xl border-t-2 border-[#EC4899]",
    headerBg: "bg-[#1C0E38]/80 backdrop-blur-xl",
    pillBg: "bg-[#2D1654]",
    pillHover: "hover:bg-[#3D1E72] hover:shadow-[0_0_15px_rgba(236,72,153,0.3)]",
    pillBorder: "border-[#EC4899]/30",
    border: "border-[#38BDF8]/30",
    accent: "text-[#38BDF8]",
    accentBg: "bg-gradient-to-r from-[#EC4899] via-[#A855F7] to-[#38BDF8]",
    accentHover: "hover:brightness-120",
    tabBg: "bg-[#160B2E]",
    tabActiveBg: "bg-[#351A62] shadow-[0_0_10px_rgba(236,72,153,0.25)] border border-[#EC4899]/40",
    tabActiveText: "text-[#38BDF8] font-bold",
    tabInactiveText: "text-[#F472B6]/70 hover:text-white",
    iconCircleBg: "bg-[#2D1654] border border-[#EC4899]/30",
    iconCircleColor: "text-[#38BDF8]",
    qrContainerBg: "bg-[#160B2E]",
    gradient: "from-pink-900/30 via-purple-900/25 to-sky-900/20",
    avatarBg: "bg-gradient-to-tr from-[#EC4899] via-[#A855F7] to-[#38BDF8]",
    avatarBorder: "border-[#EC4899]",
    divider: "bg-[#EC4899]/20",
    previewBg: "#120826",
    previewAccent: "#EC4899",
    previewSecondary: "#38BDF8",
  },

  // 13. Swiss Editorial (Editorial / Minimal)
  "swiss-editorial": {
    id: "swiss-editorial",
    name: "Swiss Editorial",
    description: "Sharp Bauhaus grid, stark paper white & vermilion orange",
    isDark: false,
    category: "editorial",
    bg: "bg-[#FFFFFF]",
    textMain: "text-[#000000]",
    textSecondary: "text-[#52525B]",
    textMuted: "text-[#A1A1AA]",
    cardBg: "bg-[#FAFAFA] border-2 border-black",
    headerBg: "bg-white",
    pillBg: "bg-[#F4F4F5]",
    pillHover: "hover:bg-[#E4E4E7]",
    pillBorder: "border-black/[0.15]",
    border: "border-black",
    accent: "text-[#FF3B30]",
    accentBg: "bg-[#FF3B30]",
    accentHover: "hover:bg-[#E02D22]",
    tabBg: "bg-[#F4F4F5] border border-black/10",
    tabActiveBg: "bg-black text-white",
    tabActiveText: "text-white font-bold",
    tabInactiveText: "text-black/60 hover:text-black",
    iconCircleBg: "bg-white border border-black/10",
    iconCircleColor: "text-black",
    qrContainerBg: "bg-[#F4F4F5]",
    gradient: "from-red-100/40 via-neutral-100/30 to-transparent",
    avatarBg: "bg-black text-white",
    avatarBorder: "border-black",
    divider: "bg-black/10",
    previewBg: "#FFFFFF",
    previewAccent: "#FF3B30",
    previewSecondary: "#000000",
  },

  // 14. Tokyo Monochrome (Editorial / Minimal)
  "tokyo-monochrome": {
    id: "tokyo-monochrome",
    name: "Tokyo Ink",
    description: "Wabi-sabi sumi ink, warm rice paper & fresh wasabi green",
    isDark: true,
    category: "editorial",
    bg: "bg-[#111111]",
    textMain: "text-[#F4F4F0]",
    textSecondary: "text-[#A8A8A2]",
    textMuted: "text-[#6E6E69]",
    cardBg: "bg-[#191919]/95 backdrop-blur-2xl border border-white/[0.08]",
    headerBg: "bg-[#191919]/85 backdrop-blur-xl",
    pillBg: "bg-[#242424]",
    pillHover: "hover:bg-[#2F2F2F]",
    pillBorder: "border-white/[0.08]",
    border: "border-[#84CC16]/30",
    accent: "text-[#A3E635]",
    accentBg: "bg-[#84CC16]",
    accentHover: "hover:bg-[#65A30D]",
    tabBg: "bg-[#151515]",
    tabActiveBg: "bg-[#282828] shadow-sm border border-[#84CC16]/30",
    tabActiveText: "text-[#A3E635] font-semibold",
    tabInactiveText: "text-[#A8A8A2] hover:text-white",
    iconCircleBg: "bg-[#242424]",
    iconCircleColor: "text-[#A3E635]",
    qrContainerBg: "bg-[#151515]",
    gradient: "from-lime-950/20 via-neutral-900/40 to-transparent",
    avatarBg: "bg-gradient-to-b from-neutral-800 to-neutral-900",
    avatarBorder: "border-[#84CC16]/50",
    divider: "bg-white/[0.06]",
    previewBg: "#111111",
    previewAccent: "#84CC16",
    previewSecondary: "#242424",
  },

  // 15. Minimalist Glass (Editorial / Minimal)
  "minimalist-glass": {
    id: "minimalist-glass",
    name: "Minimalist Glass",
    description: "Ultra-clean frosted glass with subtle monochrome shadows",
    isDark: false,
    category: "editorial",
    bg: "bg-[#f8fafc]",
    textMain: "text-[#0f172a]",
    textSecondary: "text-[#475569]",
    textMuted: "text-[#94a3b8]",
    cardBg: "bg-white/50 backdrop-blur-3xl shadow-[0_8px_32px_rgba(0,0,0,0.04)] border border-white/80",
    headerBg: "bg-white/40 backdrop-blur-xl",
    pillBg: "bg-white/60 backdrop-blur-md",
    pillHover: "hover:bg-white/90",
    pillBorder: "border-white/80",
    border: "border-white/90",
    accent: "text-[#0f172a]",
    accentBg: "bg-[#0f172a]",
    accentHover: "hover:bg-[#334155]",
    tabBg: "bg-white/40 backdrop-blur-sm p-1 rounded-2xl",
    tabActiveBg: "bg-white shadow-[0_2px_10px_rgba(0,0,0,0.04)] border border-white",
    tabActiveText: "text-[#0f172a] font-semibold",
    tabInactiveText: "text-[#64748b] hover:text-[#0f172a]",
    iconCircleBg: "bg-white shadow-sm border border-white/50",
    iconCircleColor: "text-[#0f172a]",
    qrContainerBg: "bg-white/50 backdrop-blur-md border border-white/80",
    gradient: "from-slate-200/40 via-gray-100/20 to-transparent",
    avatarBg: "bg-white/80 backdrop-blur-md",
    avatarBorder: "border-white",
    divider: "bg-black/[0.04]",
    previewBg: "#f8fafc",
    previewAccent: "#0f172a",
    previewSecondary: "#CBD5E1",
  },

  // 16. Terracotta Warmth (Creative / Warm)
  "terracotta-warmth": {
    id: "terracotta-warmth",
    name: "Terracotta Warmth",
    description: "Sun-baked sandstone, warm ivory cream & burnt terracotta",
    isDark: false,
    category: "creative",
    bg: "bg-[#FAF6F0]",
    textMain: "text-[#2B1810]",
    textSecondary: "text-[#7C5A4D]",
    textMuted: "text-[#A88B7F]",
    cardBg: "bg-[#FFFDFC]/95 backdrop-blur-2xl",
    headerBg: "bg-[#FFFDFC]/85 backdrop-blur-xl",
    pillBg: "bg-[#F3ECE4]",
    pillHover: "hover:bg-[#EAE0D5]",
    pillBorder: "border-[#D9C5B2]/40",
    border: "border-[#D9C5B2]/60",
    accent: "text-[#C85A32]",
    accentBg: "bg-[#C85A32]",
    accentHover: "hover:bg-[#B34E29]",
    tabBg: "bg-[#EFE7DE]",
    tabActiveBg: "bg-white shadow-xs",
    tabActiveText: "text-[#2B1810] font-semibold",
    tabInactiveText: "text-[#7C5A4D] hover:text-[#2B1810]",
    iconCircleBg: "bg-white shadow-xs",
    iconCircleColor: "text-[#C85A32]",
    qrContainerBg: "bg-[#F3ECE4]",
    gradient: "from-orange-100/50 via-amber-50/30 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#F3ECE4] to-[#EAE0D5]",
    avatarBorder: "border-[#C85A32]/30",
    divider: "bg-[#D9C5B2]/40",
    previewBg: "#FAF6F0",
    previewAccent: "#C85A32",
    previewSecondary: "#D9C5B2",
  },

  // 17. Nordic Polar (Editorial / Clean)
  "nordic-polar": {
    id: "nordic-polar",
    name: "Nordic Polar",
    description: "Crisp arctic ice mist with deep navy & oceanic cobalt",
    isDark: false,
    category: "editorial",
    bg: "bg-[#F0F4F8]",
    textMain: "text-[#0F172A]",
    textSecondary: "text-[#475569]",
    textMuted: "text-[#94A3B8]",
    cardBg: "bg-white/95 backdrop-blur-2xl",
    headerBg: "bg-white/85 backdrop-blur-xl",
    pillBg: "bg-[#E2E8F0]",
    pillHover: "hover:bg-[#CBD5E1]",
    pillBorder: "border-[#94A3B8]/20",
    border: "border-[#3B82F6]/20",
    accent: "text-[#2563EB]",
    accentBg: "bg-[#2563EB]",
    accentHover: "hover:bg-[#1D4ED8]",
    tabBg: "bg-[#E2E8F0]",
    tabActiveBg: "bg-white shadow-xs",
    tabActiveText: "text-[#0F172A] font-semibold",
    tabInactiveText: "text-[#64748B] hover:text-[#0F172A]",
    iconCircleBg: "bg-white shadow-xs",
    iconCircleColor: "text-[#2563EB]",
    qrContainerBg: "bg-[#E2E8F0]",
    gradient: "from-sky-100/60 via-blue-50/40 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#E2E8F0] to-[#CBD5E1]",
    avatarBorder: "border-[#2563EB]/30",
    divider: "bg-[#94A3B8]/20",
    previewBg: "#F0F4F8",
    previewAccent: "#2563EB",
    previewSecondary: "#CBD5E1",
  },

  // 18. Matcha & Cream (Creative / Warm)
  "matcha-latte": {
    id: "matcha-latte",
    name: "Matcha Cream",
    description: "Kyoto matcha green, warm oat milk & bamboo sage",
    isDark: false,
    category: "creative",
    bg: "bg-[#F4F6F0]",
    textMain: "text-[#1F2E1E]",
    textSecondary: "text-[#5C755A]",
    textMuted: "text-[#8FA68D]",
    cardBg: "bg-[#FCFDFB]/95 backdrop-blur-2xl",
    headerBg: "bg-[#FCFDFB]/85 backdrop-blur-xl",
    pillBg: "bg-[#E9EDE3]",
    pillHover: "hover:bg-[#DFE4D8]",
    pillBorder: "border-[#5C755A]/20",
    border: "border-[#5C755A]/25",
    accent: "text-[#4D7C0F]",
    accentBg: "bg-[#4D7C0F]",
    accentHover: "hover:bg-[#3F6212]",
    tabBg: "bg-[#E6EBE0]",
    tabActiveBg: "bg-white shadow-xs",
    tabActiveText: "text-[#1F2E1E] font-semibold",
    tabInactiveText: "text-[#5C755A] hover:text-[#1F2E1E]",
    iconCircleBg: "bg-white shadow-xs",
    iconCircleColor: "text-[#4D7C0F]",
    qrContainerBg: "bg-[#E9EDE3]",
    gradient: "from-emerald-100/40 via-lime-50/30 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#E9EDE3] to-[#DFE4D8]",
    avatarBorder: "border-[#4D7C0F]/40",
    divider: "bg-[#5C755A]/15",
    previewBg: "#F4F6F0",
    previewAccent: "#4D7C0F",
    previewSecondary: "#A3E635",
  },

  // 19. Electric Coral (Creative / Vibrant)
  "electric-coral": {
    id: "electric-coral",
    name: "Electric Coral",
    description: "Deep charcoal, electric coral red & bright tangerine",
    isDark: true,
    category: "creative",
    bg: "bg-[#0E0F12]",
    textMain: "text-[#FFF5F5]",
    textSecondary: "text-[#FDA4AF]",
    textMuted: "text-[#FB7185]/60",
    cardBg: "bg-[#181920]/95 backdrop-blur-2xl",
    headerBg: "bg-[#181920]/85 backdrop-blur-xl",
    pillBg: "bg-[#252632]",
    pillHover: "hover:bg-[#323344]",
    pillBorder: "border-[#F43F5E]/25",
    border: "border-[#FB923C]/30",
    accent: "text-[#FB7185]",
    accentBg: "bg-gradient-to-r from-[#F43F5E] to-[#FB923C]",
    accentHover: "hover:brightness-110",
    tabBg: "bg-[#121319]",
    tabActiveBg: "bg-[#2A2B3A] shadow-sm border border-[#F43F5E]/30",
    tabActiveText: "text-[#FFF5F5] font-semibold",
    tabInactiveText: "text-[#FDA4AF]/70 hover:text-white",
    iconCircleBg: "bg-[#252632] border border-[#F43F5E]/20",
    iconCircleColor: "text-[#FB7185]",
    qrContainerBg: "bg-[#121319]",
    gradient: "from-rose-900/30 via-orange-900/15 to-transparent",
    avatarBg: "bg-gradient-to-br from-[#F43F5E] to-[#FB923C]",
    avatarBorder: "border-[#FB923C]/60",
    divider: "bg-[#F43F5E]/15",
    previewBg: "#0E0F12",
    previewAccent: "#F43F5E",
    previewSecondary: "#FB923C",
  },

  // 20. Sunset Horizon (Creative / Vibrant)
  "sunset-horizon": {
    id: "sunset-horizon",
    name: "Sunset Horizon",
    description: "Californian twilight gradient, neon peach & magenta",
    isDark: true,
    category: "creative",
    bg: "bg-[#0C0814]",
    textMain: "text-[#FFFFFF]",
    textSecondary: "text-[#FED7AA]",
    textMuted: "text-[#FB923C]/70",
    cardBg: "bg-[#191026]/90 backdrop-blur-2xl border-t border-[#F43F5E]/40",
    headerBg: "bg-[#191026]/80 backdrop-blur-xl",
    pillBg: "bg-[#281A3E]",
    pillHover: "hover:bg-[#382456]",
    pillBorder: "border-[#FB923C]/25",
    border: "border-[#F43F5E]/30",
    accent: "text-[#FB923C]",
    accentBg: "bg-gradient-to-r from-[#F43F5E] via-[#D946EF] to-[#FB923C]",
    accentHover: "hover:brightness-115",
    tabBg: "bg-[#130B20]",
    tabActiveBg: "bg-[#33204E] shadow-sm border border-[#FB923C]/30",
    tabActiveText: "text-[#FED7AA] font-semibold",
    tabInactiveText: "text-[#F43F5E]/70 hover:text-white",
    iconCircleBg: "bg-[#281A3E] border border-[#FB923C]/20",
    iconCircleColor: "text-[#FB923C]",
    qrContainerBg: "bg-[#130B20]",
    gradient: "from-rose-900/30 via-fuchsia-900/25 to-amber-900/20",
    avatarBg: "bg-gradient-to-tr from-[#F43F5E] via-[#D946EF] to-[#FB923C]",
    avatarBorder: "border-[#FB923C]/60",
    divider: "bg-[#FB923C]/20",
    previewBg: "#0C0814",
    previewAccent: "#F43F5E",
    previewSecondary: "#FB923C",
  },

  // 21. Frost Lavender (Light & Frost)
  "frost-lavender": {
    id: "frost-lavender",
    name: "Frost Lavender",
    description: "Frosted lilac mist, clean milk white & pastel indigo",
    isDark: false,
    category: "light",
    bg: "bg-[#F7F6FB]",
    textMain: "text-[#1E1B2E]",
    textSecondary: "text-[#6B658B]",
    textMuted: "text-[#9E98BE]",
    cardBg: "bg-white/95 backdrop-blur-2xl",
    headerBg: "bg-white/85 backdrop-blur-xl",
    pillBg: "bg-[#EFEBF8]",
    pillHover: "hover:bg-[#E4DCF3]",
    pillBorder: "border-[#7C3AED]/15",
    border: "border-[#7C3AED]/20",
    accent: "text-[#7C3AED]",
    accentBg: "bg-[#7C3AED]",
    accentHover: "hover:bg-[#6D28D9]",
    tabBg: "bg-[#ECE6F6]",
    tabActiveBg: "bg-white shadow-xs",
    tabActiveText: "text-[#1E1B2E] font-semibold",
    tabInactiveText: "text-[#6B658B] hover:text-[#1E1B2E]",
    iconCircleBg: "bg-white shadow-xs",
    iconCircleColor: "text-[#7C3AED]",
    qrContainerBg: "bg-[#EFEBF8]",
    gradient: "from-purple-100/50 via-indigo-50/40 to-transparent",
    avatarBg: "bg-gradient-to-b from-[#EFEBF8] to-[#E4DCF3]",
    avatarBorder: "border-[#7C3AED]/30",
    divider: "bg-[#7C3AED]/15",
    previewBg: "#F7F6FB",
    previewAccent: "#7C3AED",
    previewSecondary: "#C4B5FD",
  },

  // 22. Midnight Crimson (Dark OLED)
  "midnight-crimson": {
    id: "midnight-crimson",
    name: "Midnight Crimson",
    description: "Deep blood moon velvet, matte black & crimson scarlet",
    isDark: true,
    category: "dark",
    bg: "bg-[#090506]",
    textMain: "text-[#FFF0F2]",
    textSecondary: "text-[#FDA4AF]",
    textMuted: "text-[#9F1239]/70",
    cardBg: "bg-[#140A0D]/95 backdrop-blur-2xl border-t border-[#E11D48]/30",
    headerBg: "bg-[#140A0D]/85 backdrop-blur-xl",
    pillBg: "bg-[#220F15]",
    pillHover: "hover:bg-[#321620]",
    pillBorder: "border-[#E11D48]/25",
    border: "border-[#E11D48]/35",
    accent: "text-[#F43F5E]",
    accentBg: "bg-gradient-to-r from-[#E11D48] to-[#BE123C]",
    accentHover: "hover:brightness-115",
    tabBg: "bg-[#0F0609]",
    tabActiveBg: "bg-[#291119] shadow-sm border border-[#E11D48]/30",
    tabActiveText: "text-[#FFF0F2] font-semibold",
    tabInactiveText: "text-[#FDA4AF]/70 hover:text-white",
    iconCircleBg: "bg-[#220F15] border border-[#E11D48]/25",
    iconCircleColor: "text-[#F43F5E]",
    qrContainerBg: "bg-[#0F0609]",
    gradient: "from-rose-950/40 via-red-950/20 to-transparent",
    avatarBg: "bg-gradient-to-br from-[#E11D48] to-[#140A0D]",
    avatarBorder: "border-[#E11D48]/60",
    divider: "bg-[#E11D48]/20",
    previewBg: "#090506",
    previewAccent: "#E11D48",
    previewSecondary: "#BE123C",
  },
};

// Aliases for backwards-compatibility with previous cards
themes["midnight-glass"] = themes["titanium-slate"];
themes["sync-sphere"] = themes["cosmic-nebula"];

export const themeList: ThemeTokens[] = Object.values(themes).filter(
  (v, i, a) => a.findIndex(t => t.id === v.id) === i
);
