export const themes: Record<string, Record<string, string>> = {
  "apple-light": {
    bg: "bg-[#F5F5F7]",
    textMain: "text-[#1D1D1F]",
    textSecondary: "text-[#86868B]",
    cardBg: "bg-white/90",
    headerBg: "bg-white/80",
    pillBg: "bg-[#F5F5F7]",
    pillHover: "hover:bg-[#E8E8ED]",
    accent: "text-[#0071E3]",
    accentBg: "bg-[#0071E3]",
    accentHover: "hover:bg-[#0077ED]",
    border: "border-black/[0.08]",
    pillBorder: "border-black/[0.04]",
    tabBg: "bg-[#EFEFF4]",
    tabActiveBg: "bg-white",
    qrBg: "bg-white",
    gradient: "from-blue-100/50 via-purple-50/20",
    iconBg: "bg-white",
    buttonText: "text-white"
  },
  "apple-dark": {
    bg: "bg-black",
    textMain: "text-white",
    textSecondary: "text-[#A1A1A6]",
    cardBg: "bg-[#1C1C1E]/90",
    headerBg: "bg-[#1C1C1E]/80",
    pillBg: "bg-[#2C2C2E]",
    pillHover: "hover:bg-[#3A3A3C]",
    accent: "text-[#0A84FF]",
    accentBg: "bg-[#0A84FF]",
    accentHover: "hover:bg-[#0071E3]",
    border: "border-white/[0.08]",
    pillBorder: "border-white/[0.04]",
    tabBg: "bg-[#2C2C2E]",
    tabActiveBg: "bg-[#48484A]",
    qrBg: "bg-white", 
    gradient: "from-blue-900/20 via-purple-900/10",
    iconBg: "bg-[#3A3A3C]",
    buttonText: "text-white"
  },
  "midnight-glass": {
    bg: "bg-slate-900",
    textMain: "text-slate-50",
    textSecondary: "text-slate-400",
    cardBg: "bg-white/10",
    headerBg: "bg-white/10",
    pillBg: "bg-white/5",
    pillHover: "hover:bg-white/10",
    accent: "text-indigo-400",
    accentBg: "bg-indigo-500",
    accentHover: "hover:bg-indigo-600",
    border: "border-white/10",
    pillBorder: "border-white/5",
    tabBg: "bg-black/20",
    tabActiveBg: "bg-white/10",
    qrBg: "bg-white",
    gradient: "from-indigo-900/40 via-purple-900/20",
    iconBg: "bg-white/10",
    buttonText: "text-white"
  },

  "sync-sphere": {
    bg: "bg-[#050507]",
    textMain: "text-white",
    textSecondary: "text-[#94A3B8]",
    cardBg: "bg-[#121216]/60 backdrop-blur-xl",
    headerBg: "bg-[#121216]/80 backdrop-blur-xl",
    pillBg: "bg-white/5",
    pillHover: "hover:bg-white/10",
    accent: "text-[#8b5cf6]",
    accentBg: "bg-[#8b5cf6]",
    accentHover: "hover:bg-[#ec4899]",
    border: "border-white/10",
    pillBorder: "border-white/5",
    tabBg: "bg-white/5",
    tabActiveBg: "bg-white/10",
    qrBg: "bg-[#1A1A20]",
    gradient: "from-violet-500/20 via-pink-500/10",
    iconBg: "bg-white/5",
    buttonText: "text-white"
  }

};
